Imports System
Imports System.Collections.Generic

Namespace Services
    ''' <summary>
    ''' تعريف عمود في قاعدة البيانات لغرض الفحص والترقيع التلقائي (Self-Healing)
    ''' </summary>
    Public Class ColumnDefinition
        Public Property Name As String
        Public Property SqlType As String
        Public Property IsNullable As Boolean = True
        Public Property DefaultValue As String = Nothing
        Public Property IsIdentity As Boolean = False
        Public Property IsPrimaryKey As Boolean = False

        Public Sub New()
        End Sub

        Public Sub New(name As String, sqlType As String, Optional isNullable As Boolean = True, Optional defaultValue As String = Nothing, Optional isIdentity As Boolean = False, Optional isPrimaryKey As Boolean = False)
            Me.Name = name
            Me.SqlType = sqlType
            Me.IsNullable = isNullable
            Me.DefaultValue = defaultValue
            Me.IsIdentity = isIdentity
            Me.IsPrimaryKey = isPrimaryKey
        End Sub

        ''' <summary>
        ''' توليد جملة تعريف العمود داخل CREATE TABLE
        ''' </summary>
        Public Function ToColumnDefinitionSql() As String
            Dim identityPart As String = If(IsIdentity, " IDENTITY(1,1)", "")
            Dim nullPart As String = If(IsNullable, " NULL", " NOT NULL")
            Dim defaultPart As String = If(Not String.IsNullOrEmpty(DefaultValue), $" DEFAULT {DefaultValue}", "")
            Return $"[{Name}] {SqlType}{identityPart}{nullPart}{defaultPart}"
        End Function

        ''' <summary>
        ''' توليد جملة ALTER TABLE ... ADD بأمان مع معالجة القيمة الافتراضية
        ''' </summary>
        Public Function ToAlterTableAddSql(tableName As String) As String
            Dim nullPart As String = If(IsNullable, " NULL", " NOT NULL")
            Dim defaultPart As String = ""

            If Not String.IsNullOrEmpty(DefaultValue) Then
                If Not IsNullable Then
                    defaultPart = $" DEFAULT {DefaultValue} WITH VALUES"
                Else
                    defaultPart = $" DEFAULT {DefaultValue}"
                End If
            ElseIf Not IsNullable Then
                nullPart = " NULL"
            End If

            Return $"ALTER TABLE [{tableName}] ADD [{Name}] {SqlType}{nullPart}{defaultPart};"
        End Function
    End Class

    ''' <summary>
    ''' تعريف جدول كامل في قاعدة البيانات
    ''' </summary>
    Public Class TableDefinition
        Public Property TableName As String
        Public Property DisplayNameAr As String
        Public Property DisplayNameEn As String
        Public Property IsTransactional As Boolean = False
        Public Property Columns As New List(Of ColumnDefinition)()
        Public Property PrimaryKeys As New List(Of String)()

        Public Sub New()
        End Sub

        Public Sub New(tableName As String, displayNameAr As String, displayNameEn As String, Optional isTransactional As Boolean = False)
            Me.TableName = tableName
            Me.DisplayNameAr = displayNameAr
            Me.DisplayNameEn = displayNameEn
            Me.IsTransactional = isTransactional
        End Sub

        Public Function AddColumn(name As String, sqlType As String, Optional isNullable As Boolean = True, Optional defaultValue As String = Nothing, Optional isIdentity As Boolean = False, Optional isPrimaryKey As Boolean = False) As TableDefinition
            Columns.Add(New ColumnDefinition(name, sqlType, isNullable, defaultValue, isIdentity, isPrimaryKey))
            If isPrimaryKey AndAlso Not PrimaryKeys.Contains(name) Then
                PrimaryKeys.Add(name)
            End If
            Return Me
        End Function

        ''' <summary>
        ''' توليد أمر CREATE TABLE كامل للجدول
        ''' </summary>
        Public Function ToCreateTableSql() As String
            Dim colDefs As New List(Of String)()
            For Each col In Columns
                colDefs.Add("    " & col.ToColumnDefinitionSql())
            Next

            If PrimaryKeys.Count > 0 Then
                Dim pkList = String.Join(", ", PrimaryKeys.ConvertAll(Function(p) $"[{p}]"))
                colDefs.Add($"    CONSTRAINT PK_{TableName} PRIMARY KEY ({pkList})")
            End If

            Return $"CREATE TABLE [dbo].[{TableName}] (" & vbCrLf &
                   String.Join("," & vbCrLf, colDefs) & vbCrLf &
                   ");"
        End Function
    End Class

    ''' <summary>
    ''' مستودع التعريفات الهيكلية الشامل لكافة جداول وأعمدة النظام الـ 74
    ''' المتطابقة 100% مع قاعدة البيانات الفعلية SestamkDB ومحرك LocalDB
    ''' </summary>
    Public Module DatabaseSchemaDefinitions
        Private _schemaTables As List(Of TableDefinition) = Nothing
        Private ReadOnly _lockObj As New Object()

        Public Function GetExpectedSchema() As List(Of TableDefinition)
            If _schemaTables IsNot Nothing Then Return _schemaTables

            SyncLock _lockObj
                If _schemaTables IsNot Nothing Then Return _schemaTables

                Dim list As New List(Of TableDefinition)()
                Dim t As TableDefinition = Nothing

                ' 1. Addons (الإضافات والخيارات)
                t = New TableDefinition("Addons", "الإضافات والخيارات", "Addons", False)
                t.AddColumn("AddonID", "INT", False, Nothing, True, True)
                t.AddColumn("AddonCode", "NVARCHAR(20)", True, Nothing, False, False)
                t.AddColumn("AddonNameAr", "NVARCHAR(100)", False, Nothing, False, False)
                t.AddColumn("AddonNameEn", "NVARCHAR(100)", True, Nothing, False, False)
                t.AddColumn("IsActive", "BIT", False, "1", False, False)
                t.AddColumn("IsDeleted", "BIT", False, "0", False, False)
                t.AddColumn("CreatedAt", "DATETIME2", False, "getdate()", False, False)
                list.Add(t)

                ' 2. AppScreens (شاشات النظام)
                t = New TableDefinition("AppScreens", "شاشات النظام", "Application Screens", False)
                t.AddColumn("ScreenID", "INT", False, Nothing, True, True)
                t.AddColumn("FormName", "NVARCHAR(100)", False, Nothing, False, False)
                t.AddColumn("ScreenDisplayName", "NVARCHAR(150)", False, Nothing, False, False)
                t.AddColumn("Category", "NVARCHAR(100)", False, Nothing, False, False)
                list.Add(t)

                ' 3. AppSettings (إعدادات النظام)
                t = New TableDefinition("AppSettings", "إعدادات النظام", "System Settings", False)
                t.AddColumn("ID", "INT", False, Nothing, True, True)
                t.AddColumn("SettingKey", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("SettingValue", "NVARCHAR(MAX)", True, Nothing, False, False)
                list.Add(t)

                ' 4. BRANCH_TBL (الفروع (توافقي))
                t = New TableDefinition("BRANCH_TBL", "الفروع (توافقي)", "Branches (Legacy)", False)
                t.AddColumn("BRAN_ID", "NUMERIC(18, 0)", False, Nothing, False, True)
                t.AddColumn("BRAN_CODE", "NUMERIC(18, 0)", True, Nothing, False, False)
                t.AddColumn("BRAN_NAME", "VARCHAR(50)", True, Nothing, False, False)
                t.AddColumn("BRAN_ADDRESS", "VARCHAR(50)", True, Nothing, False, False)
                t.AddColumn("BRAN_PHONE", "VARCHAR(50)", True, Nothing, False, False)
                t.AddColumn("BRAN_MOBILE", "VARCHAR(50)", True, Nothing, False, False)
                t.AddColumn("BRAN_OPENDATE", "DATE", True, Nothing, False, False)
                t.AddColumn("BRAN_STATE", "INT", True, Nothing, False, False)
                t.AddColumn("Com_ID", "NUMERIC(18, 0)", True, Nothing, False, False)
                list.Add(t)

                ' 5. Backup_Log (سجل النسخ الاحتياطي)
                t = New TableDefinition("Backup_Log", "سجل النسخ الاحتياطي", "Backup Log", False)
                t.AddColumn("Backup_ID", "INT", False, Nothing, True, True)
                t.AddColumn("Backup_File", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Backup_Date", "DATETIME", True, "getdate()", False, False)
                t.AddColumn("Backup_By", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Backup_Slot", "INT", True, Nothing, False, False)
                t.AddColumn("Backup_Size", "NVARCHAR(50)", True, Nothing, False, False)
                list.Add(t)

                ' 6. Branches (الفروع ومراكز البيع)
                t = New TableDefinition("Branches", "الفروع ومراكز البيع", "Branches", False)
                t.AddColumn("BranchID", "INT", False, Nothing, True, True)
                t.AddColumn("BranchCode", "NVARCHAR(20)", True, Nothing, False, False)
                t.AddColumn("BranchName", "NVARCHAR(150)", False, Nothing, False, False)
                t.AddColumn("Phone", "NVARCHAR(30)", True, Nothing, False, False)
                t.AddColumn("Mobile", "NVARCHAR(30)", True, Nothing, False, False)
                t.AddColumn("Address", "NVARCHAR(500)", True, Nothing, False, False)
                t.AddColumn("Notes", "NVARCHAR(500)", True, Nothing, False, False)
                t.AddColumn("IsMainBranch", "BIT", False, "0", False, False)
                t.AddColumn("IsActive", "BIT", False, "1", False, False)
                t.AddColumn("IsDeleted", "BIT", False, "0", False, False)
                t.AddColumn("ManagerEmployeeID", "INT", True, Nothing, False, False)
                t.AddColumn("CreatedAt", "DATETIME2", False, "getdate()", False, False)
                t.AddColumn("CreatedBy", "INT", True, Nothing, False, False)
                t.AddColumn("IsDefault", "BIT", False, "0", False, False)
                list.Add(t)

                ' 7. Categories (الأقسام والمجموعات)
                t = New TableDefinition("Categories", "الأقسام والمجموعات", "Categories", False)
                t.AddColumn("Category_ID", "INT", False, Nothing, True, True)
                t.AddColumn("CategoryCode", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Category_NameAr", "NVARCHAR(MAX)", False, Nothing, False, False)
                t.AddColumn("CategoryNameEn", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Imagebase64", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Description", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("IsActive", "BIT", True, Nothing, False, False)
                t.AddColumn("IsDeleted", "BIT", True, Nothing, False, False)
                t.AddColumn("ColorID", "INT", True, Nothing, False, False)
                t.AddColumn("CategoryTypeID", "INT", True, Nothing, False, False)
                t.AddColumn("PrinterID", "INT", True, Nothing, False, False)
                t.AddColumn("CategoryID", "INT", True, Nothing, False, False)
                t.AddColumn("CategoryName", "NVARCHAR(150)", True, Nothing, False, False)
                t.AddColumn("Category_Name", "NVARCHAR(150)", True, Nothing, False, False)
                t.AddColumn("CreatedAt", "DATETIME", False, "getdate()", False, False)
                list.Add(t)

                ' 8. CategoryTypes (أنواع وتصنيفات الأقسام)
                t = New TableDefinition("CategoryTypes", "أنواع وتصنيفات الأقسام", "Category Types", False)
                t.AddColumn("CategoryTypeID", "INT", False, Nothing, True, True)
                t.AddColumn("TypeCode", "NVARCHAR(20)", True, Nothing, False, False)
                t.AddColumn("TypeName", "NVARCHAR(MAX)", False, Nothing, False, False)
                t.AddColumn("IsActive", "BIT", True, Nothing, False, False)
                t.AddColumn("IsDeleted", "BIT", True, "0", False, False)
                list.Add(t)

                ' 9. Colors (ألوان الواجهة والأقسام)
                t = New TableDefinition("Colors", "ألوان الواجهة والأقسام", "Colors", False)
                t.AddColumn("ColorID", "INT", False, Nothing, True, True)
                t.AddColumn("ColorCode", "NVARCHAR(30)", True, Nothing, False, False)
                t.AddColumn("ColorName", "NVARCHAR(100)", True, Nothing, False, False)
                t.AddColumn("HexCode", "NVARCHAR(20)", True, Nothing, False, False)
                t.AddColumn("IsActive", "BIT", True, "1", False, False)
                t.AddColumn("IsDeleted", "BIT", True, "0", False, False)
                t.AddColumn("Notes", "NVARCHAR(250)", True, Nothing, False, False)
                list.Add(t)

                ' 10. Company_info_TBL (بيانات المنشأة والترويسة)
                t = New TableDefinition("Company_info_TBL", "بيانات المنشأة والترويسة", "Company Info", False)
                t.AddColumn("Com_ID", "NUMERIC(18, 0)", False, Nothing, False, True)
                t.AddColumn("Com_Code", "NUMERIC(18, 0)", True, Nothing, False, False)
                t.AddColumn("Com_NAME", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Com_ADDRESS1", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Com_ADDRESS2", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Com_ADDRESS3", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Com_Mobile1", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Com_Mobile2", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Com_Mobile3", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Com_FAX", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Com_Title", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Com_Note", "NVARCHAR(MAX)", True, Nothing, False, False)
                list.Add(t)

                ' 11. Customer (العملاء (توافقي))
                t = New TableDefinition("Customer", "العملاء (توافقي)", "Customer (Legacy)", False)
                t.AddColumn("CustomerID", "INT", False, Nothing, True, True)
                t.AddColumn("CustomerCode", "NVARCHAR(50)", True, Nothing, False, False)
                t.AddColumn("CustomerName", "NVARCHAR(150)", False, Nothing, False, False)
                t.AddColumn("Phone", "NVARCHAR(50)", True, Nothing, False, False)
                t.AddColumn("PhoneNumber", "NVARCHAR(50)", True, Nothing, False, False)
                t.AddColumn("Address", "NVARCHAR(250)", True, Nothing, False, False)
                t.AddColumn("CreditLimit", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("Balance", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("CurrentBalance", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("Notes", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("IsActive", "BIT", False, "1", False, False)
                t.AddColumn("IsDeleted", "BIT", False, "0", False, False)
                t.AddColumn("CreatedAt", "DATETIME", False, "getdate()", False, False)
                list.Add(t)

                ' 12. CustomerBalanceLog (سجل تدقيق أرصدة العملاء)
                t = New TableDefinition("CustomerBalanceLog", "سجل تدقيق أرصدة العملاء", "Customer Balance Log", True)
                t.AddColumn("LogID", "INT", False, Nothing, True, False)
                t.AddColumn("CustomerID", "INT", True, Nothing, False, False)
                t.AddColumn("CustomerCode", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("CustomerName", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("OldBalance", "DECIMAL(18, 2)", True, Nothing, False, False)
                t.AddColumn("PaidAmount", "DECIMAL(18, 2)", True, Nothing, False, False)
                t.AddColumn("NewBalance", "DECIMAL(18, 2)", True, Nothing, False, False)
                t.AddColumn("Notes", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("UserName", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("ActionDate", "DATETIME", True, Nothing, False, False)
                list.Add(t)

                ' 13. CustomerTransactions (حركات وكشوف حساب العملاء)
                t = New TableDefinition("CustomerTransactions", "حركات وكشوف حساب العملاء", "Customer Transactions", True)
                t.AddColumn("TransactionID", "INT", False, Nothing, True, True)
                t.AddColumn("TransactionDate", "DATETIME", False, "getdate()", False, False)
                t.AddColumn("CustomerID", "INT", False, Nothing, False, False)
                t.AddColumn("InvoiceID", "INT", True, Nothing, False, False)
                t.AddColumn("TransactionType", "NVARCHAR(50)", False, Nothing, False, False)
                t.AddColumn("Debit", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("Credit", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("BalanceAfter", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("Notes", "NVARCHAR(500)", True, Nothing, False, False)
                t.AddColumn("ShiftID", "INT", True, Nothing, False, False)
                t.AddColumn("UserID", "INT", False, Nothing, False, False)
                t.AddColumn("CreatedAt", "DATETIME", False, "getdate()", False, False)
                t.AddColumn("BranchID", "INT", True, Nothing, False, False)
                list.Add(t)

                ' 14. Customer_Account_TBL (حسابات العملاء (توافقي))
                t = New TableDefinition("Customer_Account_TBL", "حسابات العملاء (توافقي)", "Customer Accounts (Legacy)", False)
                t.AddColumn("Cust_A_ID", "NUMERIC(18, 0)", False, Nothing, False, True)
                t.AddColumn("Cust_A_Code", "NUMERIC(18, 0)", True, Nothing, False, False)
                t.AddColumn("Cust_A_Name", "VARCHAR(200)", True, Nothing, False, False)
                t.AddColumn("Cust_A_N_Name", "VARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Cust_A_Date", "DATE", True, Nothing, False, False)
                t.AddColumn("Cust_A_Dept", "DECIMAL(18, 2)", True, Nothing, False, False)
                t.AddColumn("Trd_ID", "NUMERIC(18, 0)", True, Nothing, False, False)
                t.AddColumn("Cust_A_State", "BIT", True, Nothing, False, False)
                t.AddColumn("Cust_A_Note", "VARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Cust_ID", "NUMERIC(18, 0)", True, Nothing, False, False)
                list.Add(t)

                ' 15. Customer_TBL (العملاء (توافقي))
                t = New TableDefinition("Customer_TBL", "العملاء (توافقي)", "Customers Table (Legacy)", False)
                t.AddColumn("Cust_ID", "NUMERIC(18, 0)", False, Nothing, False, True)
                t.AddColumn("Cust_Code", "NUMERIC(18, 0)", True, Nothing, False, False)
                t.AddColumn("Cust_Name", "VARCHAR(200)", True, Nothing, False, False)
                t.AddColumn("Cust_N_Name", "VARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Cust_S_Date", "DATE", True, Nothing, False, False)
                t.AddColumn("Cust_Major", "VARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Cust_Address", "VARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Cust_Mobile", "VARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Cust_Mobile1", "VARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Cust_State", "BIT", True, Nothing, False, False)
                t.AddColumn("Cust_Note", "VARCHAR(MAX)", True, Nothing, False, False)
                list.Add(t)

                ' 16. Customers (سجل العملاء والمديونيات)
                t = New TableDefinition("Customers", "سجل العملاء والمديونيات", "Customers", False)
                t.AddColumn("CustomerID", "INT", False, Nothing, True, True)
                t.AddColumn("CustomerCode", "NVARCHAR(50)", True, Nothing, False, False)
                t.AddColumn("CustomerName", "NVARCHAR(100)", True, Nothing, False, False)
                t.AddColumn("Phone1", "NVARCHAR(20)", True, Nothing, False, False)
                t.AddColumn("Phone2", "NVARCHAR(20)", True, Nothing, False, False)
                t.AddColumn("Email", "NVARCHAR(100)", True, Nothing, False, False)
                t.AddColumn("AreaID", "INT", True, Nothing, False, False)
                t.AddColumn("Address", "NVARCHAR(255)", True, Nothing, False, False)
                t.AddColumn("CurrentBalance", "DECIMAL(18, 2)", True, "0", False, False)
                t.AddColumn("AllowCredit", "BIT", True, "1", False, False)
                t.AddColumn("CreditLimit", "DECIMAL(18, 2)", True, "0", False, False)
                t.AddColumn("IsDiscountPercent", "BIT", True, Nothing, False, False)
                t.AddColumn("DiscountPercent", "FLOAT", True, "0", False, False)
                t.AddColumn("IsDeleted", "BIT", True, "0", False, False)
                t.AddColumn("IsActive", "BIT", True, "1", False, False)
                t.AddColumn("StopReason", "NVARCHAR(255)", True, Nothing, False, False)
                t.AddColumn("Rating", "TINYINT", True, "5", False, False)
                t.AddColumn("Notes", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("CreatedDate", "DATETIME", True, "getdate()", False, False)
                t.AddColumn("CreatedByUserID", "INT", True, Nothing, False, False)
                t.AddColumn("LastTransactionDate", "DATETIME", True, Nothing, False, False)
                t.AddColumn("Phone", "NVARCHAR(50)", True, Nothing, False, False)
                t.AddColumn("Balance", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("CreatedAt", "DATETIME", False, "getdate()", False, False)
                t.AddColumn("PhoneNumber", "NVARCHAR(50)", True, Nothing, False, False)
                list.Add(t)

                ' 17. DeliveryAreas (مناطق التوصيل والرسوم)
                t = New TableDefinition("DeliveryAreas", "مناطق التوصيل والرسوم", "Delivery Areas", False)
                t.AddColumn("AreaID", "INT", False, Nothing, True, True)
                t.AddColumn("AreaCode", "NVARCHAR(20)", True, Nothing, False, False)
                t.AddColumn("AreaName", "NVARCHAR(100)", False, Nothing, False, False)
                t.AddColumn("Notes", "NVARCHAR(250)", True, Nothing, False, False)
                t.AddColumn("IsActive", "BIT", False, "1", False, False)
                t.AddColumn("IsDeleted", "BIT", False, "0", False, False)
                t.AddColumn("CreatedAt", "DATETIME2", False, "getdate()", False, False)
                t.AddColumn("DeliveryFee", "DECIMAL(18, 2)", False, "0", False, False)
                list.Add(t)

                ' 18. DeliveryDrivers (سائقي وطياري الدليفري)
                t = New TableDefinition("DeliveryDrivers", "سائقي وطياري الدليفري", "Delivery Drivers", False)
                t.AddColumn("DriverID", "INT", False, Nothing, True, True)
                t.AddColumn("DriverCode", "NVARCHAR(20)", False, Nothing, False, False)
                t.AddColumn("DriverName", "NVARCHAR(150)", False, Nothing, False, False)
                t.AddColumn("Phone", "NVARCHAR(20)", False, Nothing, False, False)
                t.AddColumn("Phone2", "NVARCHAR(20)", True, Nothing, False, False)
                t.AddColumn("NationalID", "NVARCHAR(20)", True, Nothing, False, False)
                t.AddColumn("EmployeeID", "INT", True, Nothing, False, False)
                t.AddColumn("LicenseNumber", "NVARCHAR(50)", True, Nothing, False, False)
                t.AddColumn("VehicleType", "NVARCHAR(50)", True, Nothing, False, False)
                t.AddColumn("VehiclePlateNumber", "NVARCHAR(50)", True, Nothing, False, False)
                t.AddColumn("IsPercentage", "BIT", False, "0", False, False)
                t.AddColumn("DeliveryFeeValue", "DECIMAL(18, 2)", False, "0.00", False, False)
                t.AddColumn("DriverStatus", "TINYINT", False, "1", False, False)
                t.AddColumn("Notes", "NVARCHAR(500)", True, Nothing, False, False)
                t.AddColumn("IsActive", "BIT", False, "1", False, False)
                t.AddColumn("IsDeleted", "BIT", False, "0", False, False)
                t.AddColumn("CreatedAt", "DATETIME2", False, "getdate()", False, False)
                t.AddColumn("CreatedBy", "INT", True, Nothing, False, False)
                t.AddColumn("AreaID", "INT", True, Nothing, False, False)
                t.AddColumn("VehicleNumber", "NVARCHAR(50)", True, Nothing, False, False)
                list.Add(t)

                ' 19. Departments (أقسام المنشأة والموظفين)
                t = New TableDefinition("Departments", "أقسام المنشأة والموظفين", "Departments", False)
                t.AddColumn("DepartmentID", "INT", False, Nothing, True, True)
                t.AddColumn("DepartmentCode", "NVARCHAR(20)", True, Nothing, False, False)
                t.AddColumn("DepartmentName", "NVARCHAR(100)", False, Nothing, False, False)
                t.AddColumn("Notes", "NVARCHAR(500)", True, Nothing, False, False)
                t.AddColumn("IsActive", "BIT", False, "1", False, False)
                t.AddColumn("IsDeleted", "BIT", False, "0", False, False)
                t.AddColumn("CreatedAt", "DATETIME2", False, "getdate()", False, False)
                t.AddColumn("CreatedBy", "INT", True, Nothing, False, False)
                list.Add(t)

                ' 20. DriverTransactions (حركات وتحصيلات الدليفري)
                t = New TableDefinition("DriverTransactions", "حركات وتحصيلات الدليفري", "Driver Transactions", True)
                t.AddColumn("TransactionID", "INT", False, Nothing, True, True)
                t.AddColumn("TransactionDate", "DATETIME", False, "getdate()", False, False)
                t.AddColumn("DriverID", "INT", False, Nothing, False, False)
                t.AddColumn("InvoiceID", "INT", False, Nothing, False, False)
                t.AddColumn("OrderTotal", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("DeliveryFee", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("CollectedAmount", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("IsSettled", "BIT", False, "0", False, False)
                t.AddColumn("SettledAt", "DATETIME", True, Nothing, False, False)
                t.AddColumn("ShiftID", "INT", False, Nothing, False, False)
                t.AddColumn("UserID", "INT", False, Nothing, False, False)
                t.AddColumn("Notes", "NVARCHAR(250)", True, Nothing, False, False)
                t.AddColumn("CreatedAt", "DATETIME", False, "getdate()", False, False)
                list.Add(t)

                ' 21. Employees (الموظفين والموارد البشرية)
                t = New TableDefinition("Employees", "الموظفين والموارد البشرية", "Employees", False)
                t.AddColumn("EmployeeID", "INT", False, Nothing, True, True)
                t.AddColumn("EmployeeCode", "NVARCHAR(20)", False, Nothing, False, False)
                t.AddColumn("ArabicName", "NVARCHAR(200)", False, Nothing, False, False)
                t.AddColumn("EnglishName", "NVARCHAR(200)", True, Nothing, False, False)
                t.AddColumn("NationalID", "NVARCHAR(20)", True, Nothing, False, False)
                t.AddColumn("Phone", "NVARCHAR(20)", True, Nothing, False, False)
                t.AddColumn("Phone2", "NVARCHAR(20)", True, Nothing, False, False)
                t.AddColumn("Email", "NVARCHAR(150)", True, Nothing, False, False)
                t.AddColumn("Address", "NVARCHAR(500)", True, Nothing, False, False)
                t.AddColumn("BirthDate", "DATE", True, Nothing, False, False)
                t.AddColumn("HireDate", "DATE", False, "getdate()", False, False)
                t.AddColumn("ContractEndDate", "DATE", True, Nothing, False, False)
                t.AddColumn("BranchID", "INT", True, Nothing, False, False)
                t.AddColumn("DepartmentID", "INT", True, Nothing, False, False)
                t.AddColumn("JobTitleID", "INT", True, Nothing, False, False)
                t.AddColumn("SalarySystemID", "INT", True, Nothing, False, False)
                t.AddColumn("BasicSalary", "DECIMAL(18, 2)", False, "0.00", False, False)
                t.AddColumn("TransportationAllowance", "DECIMAL(18, 2)", False, "0.00", False, False)
                t.AddColumn("HousingAllowance", "DECIMAL(18, 2)", False, "0.00", False, False)
                t.AddColumn("OtherAllowances", "DECIMAL(18, 2)", False, "0.00", False, False)
                t.AddColumn("InsuranceStatus", "BIT", False, "0", False, False)
                t.AddColumn("InsuranceAmount", "DECIMAL(18, 2)", False, "0.00", False, False)
                t.AddColumn("OvertimeAllowed", "BIT", False, "0", False, False)
                t.AddColumn("OvertimeRate", "DECIMAL(18, 2)", False, "0.00", False, False)
                t.AddColumn("PersonalPhoto", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("NationalIDPhotofront", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("NationalIDPhotoback", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Cv", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("FingerprintCode", "NVARCHAR(50)", True, Nothing, False, False)
                t.AddColumn("EmployeeStatus", "TINYINT", False, "1", False, False)
                t.AddColumn("Gender", "TINYINT", True, Nothing, False, False)
                t.AddColumn("Notes", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("IsActive", "BIT", False, "1", False, False)
                t.AddColumn("IsDeleted", "BIT", False, "0", False, False)
                t.AddColumn("CreatedAt", "DATETIME2", False, "getdate()", False, False)
                t.AddColumn("CreatedBy", "INT", True, Nothing, False, False)
                t.AddColumn("ModifiedAt", "DATETIME2", True, Nothing, False, False)
                t.AddColumn("ModifiedBy", "INT", True, Nothing, False, False)
                t.AddColumn("DeletedAt", "DATETIME2", True, Nothing, False, False)
                t.AddColumn("DeletedBy", "INT", True, Nothing, False, False)
                t.AddColumn("CheckInTime", "TIME", True, Nothing, False, False)
                t.AddColumn("CheckOutTime", "TIME", True, Nothing, False, False)
                t.AddColumn("DailyWorkingHours", "DECIMAL(5, 2)", True, Nothing, False, False)
                list.Add(t)

                ' 22. Expenses (المصروفات العامة والتشغيلية)
                t = New TableDefinition("Expenses", "المصروفات العامة والتشغيلية", "Expenses", True)
                t.AddColumn("Expense_ID", "INT", False, Nothing, True, True)
                t.AddColumn("Expense_Date", "DATE", False, "CONVERT([date],getdate())", False, False)
                t.AddColumn("Category", "NVARCHAR(50)", True, Nothing, False, False)
                t.AddColumn("Amount", "DECIMAL(18, 2)", False, Nothing, False, False)
                t.AddColumn("Payment_Method", "NVARCHAR(50)", True, Nothing, False, False)
                t.AddColumn("Payee", "NVARCHAR(100)", True, Nothing, False, False)
                t.AddColumn("Payment_Status", "NVARCHAR(20)", True, "'Paid'", False, False)
                t.AddColumn("Notes", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Created_By", "NVARCHAR(50)", True, Nothing, False, False)
                t.AddColumn("Created_At", "DATETIME", True, "getdate()", False, False)
                t.AddColumn("UpdatedAt", "DATETIME", True, "getdate()", False, False)
                t.AddColumn("TreasuryID", "INT", True, Nothing, False, False)
                t.AddColumn("ExpenseID", "INT", True, Nothing, False, False)
                t.AddColumn("ExpenseDate", "DATETIME", False, "getdate()", False, False)
                t.AddColumn("ExpenseType", "NVARCHAR(100)", True, Nothing, False, False)
                t.AddColumn("UserID", "INT", True, Nothing, False, False)
                t.AddColumn("ShiftID", "INT", True, Nothing, False, False)
                t.AddColumn("IsDeleted", "BIT", False, "0", False, False)
                t.AddColumn("CreatedAt", "DATETIME", False, "getdate()", False, False)
                list.Add(t)

                ' 23. JobTitles (المسميات والوظائف)
                t = New TableDefinition("JobTitles", "المسميات والوظائف", "Job Titles", False)
                t.AddColumn("JobTitleID", "INT", False, Nothing, True, True)
                t.AddColumn("JobTitleCode", "NVARCHAR(20)", True, Nothing, False, False)
                t.AddColumn("JobTitleName", "NVARCHAR(100)", False, Nothing, False, False)
                t.AddColumn("DepartmentID", "INT", True, Nothing, False, False)
                t.AddColumn("Notes", "NVARCHAR(500)", True, Nothing, False, False)
                t.AddColumn("IsActive", "BIT", False, "1", False, False)
                t.AddColumn("IsDeleted", "BIT", False, "0", False, False)
                t.AddColumn("CreatedAt", "DATETIME2", False, "getdate()", False, False)
                t.AddColumn("CreatedBy", "INT", True, Nothing, False, False)
                list.Add(t)

                ' 23b. KitchenComments (تعليقات وملاحظات المطبخ)
                t = New TableDefinition("KitchenComments", "تعليقات وملاحظات المطبخ", "Kitchen Comments", False)
                t.AddColumn("CommentID", "INT", False, Nothing, True, True)
                t.AddColumn("CommentCode", "NVARCHAR(50)", True, Nothing, False, False)
                t.AddColumn("CommentText", "NVARCHAR(250)", False, Nothing, False, False)
                t.AddColumn("IsActive", "BIT", False, "1", False, False)
                t.AddColumn("IsDeleted", "BIT", False, "0", False, False)
                t.AddColumn("CreatedAt", "DATETIME", False, "getdate()", False, False)
                list.Add(t)

                ' 24. KitchenOrderDetails (تفاصيل أصناف المطبخ)
                t = New TableDefinition("KitchenOrderDetails", "تفاصيل أصناف المطبخ", "Kitchen Order Details", True)
                t.AddColumn("DetailID", "INT", False, Nothing, True, True)
                t.AddColumn("KitchenOrderID", "INT", False, Nothing, False, False)
                t.AddColumn("ProductID", "INT", False, Nothing, False, False)
                t.AddColumn("ProductName", "NVARCHAR(200)", False, Nothing, False, False)
                t.AddColumn("SizeName", "NVARCHAR(100)", True, Nothing, False, False)
                t.AddColumn("AddonsText", "NVARCHAR(500)", True, Nothing, False, False)
                t.AddColumn("Quantity", "INT", False, "1", False, False)
                t.AddColumn("Notes", "NVARCHAR(500)", True, Nothing, False, False)
                t.AddColumn("IsCompleted", "BIT", False, "0", False, False)
                t.AddColumn("StationName", "NVARCHAR(100)", True, Nothing, False, False)
                list.Add(t)

                ' 25. KitchenOrders (طلبات وشاشات المطبخ)
                t = New TableDefinition("KitchenOrders", "طلبات وشاشات المطبخ", "Kitchen Orders", True)
                t.AddColumn("KitchenOrderID", "INT", False, Nothing, True, True)
                t.AddColumn("OrderNumber", "NVARCHAR(50)", False, Nothing, False, False)
                t.AddColumn("OrderType", "TINYINT", False, "1", False, False)
                t.AddColumn("TableID", "INT", True, Nothing, False, False)
                t.AddColumn("TableName", "NVARCHAR(100)", True, Nothing, False, False)
                t.AddColumn("CustomerName", "NVARCHAR(150)", True, Nothing, False, False)
                t.AddColumn("ServerName", "NVARCHAR(100)", True, Nothing, False, False)
                t.AddColumn("CreatedAt", "DATETIME", False, "getdate()", False, False)
                t.AddColumn("Status", "TINYINT", False, "0", False, False)
                t.AddColumn("PreparationStartedAt", "DATETIME", True, Nothing, False, False)
                t.AddColumn("ReadyAt", "DATETIME", True, Nothing, False, False)
                t.AddColumn("CompletedAt", "DATETIME", True, Nothing, False, False)
                t.AddColumn("Notes", "NVARCHAR(500)", True, Nothing, False, False)
                list.Add(t)

                ' 26. KitchenWaste (هالك المطبخ والتوالف)
                t = New TableDefinition("KitchenWaste", "هالك المطبخ والتوالف", "Kitchen Waste", True)
                t.AddColumn("WasteID", "INT", False, Nothing, True, True)
                t.AddColumn("WasteNumber", "NVARCHAR(50)", False, Nothing, False, False)
                t.AddColumn("WasteDate", "DATETIME", False, "getdate()", False, False)
                t.AddColumn("WasteType", "TINYINT", False, "1", False, False)
                t.AddColumn("StoreID", "INT", False, "1", False, False)
                t.AddColumn("TotalLossAmount", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("ShiftID", "INT", True, Nothing, False, False)
                t.AddColumn("UserID", "INT", False, "1", False, False)
                t.AddColumn("ResponsibleStaffName", "NVARCHAR(150)", True, Nothing, False, False)
                t.AddColumn("Reason", "NVARCHAR(500)", True, Nothing, False, False)
                t.AddColumn("CreatedAt", "DATETIME", False, "getdate()", False, False)
                list.Add(t)

                ' 27. KitchenWasteDetails (تفاصيل هالك المطبخ)
                t = New TableDefinition("KitchenWasteDetails", "تفاصيل هالك المطبخ", "Kitchen Waste Details", True)
                t.AddColumn("DetailID", "INT", False, Nothing, True, True)
                t.AddColumn("WasteID", "INT", False, Nothing, False, False)
                t.AddColumn("MaterialID", "INT", True, Nothing, False, False)
                t.AddColumn("ProductID", "INT", True, Nothing, False, False)
                t.AddColumn("ItemName", "NVARCHAR(200)", False, Nothing, False, False)
                t.AddColumn("Quantity", "DECIMAL(18, 4)", False, "1", False, False)
                t.AddColumn("UnitName", "NVARCHAR(50)", True, Nothing, False, False)
                t.AddColumn("UnitCost", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("TotalCost", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("Notes", "NVARCHAR(500)", True, Nothing, False, False)
                list.Add(t)

                ' 28. Login_Info_TBL (سجل تسجيلات الدخول)
                t = New TableDefinition("Login_Info_TBL", "سجل تسجيلات الدخول", "Login Info Log", True)
                t.AddColumn("ID", "INT", False, Nothing, True, True)
                t.AddColumn("Login_Code", "INT", True, Nothing, False, False)
                t.AddColumn("Login_DeviceName", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Login_MacAddress", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Login_CurrentDate", "DATE", True, Nothing, False, False)
                t.AddColumn("Login_CurrentTime", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Login_Username", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Login_Password", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Login_Note", "NVARCHAR(MAX)", True, Nothing, False, False)
                list.Add(t)

                ' 29. Main_Cash_TBL (الخزينة الرئيسية (توافقي))
                t = New TableDefinition("Main_Cash_TBL", "الخزينة الرئيسية (توافقي)", "Main Cash (Legacy)", False)
                t.AddColumn("Cash_ID", "NUMERIC(18, 0)", False, Nothing, False, True)
                t.AddColumn("Cash_Code", "NUMERIC(18, 0)", True, Nothing, False, False)
                t.AddColumn("Cash_S_Date", "DATE", True, Nothing, False, False)
                t.AddColumn("Cash_S_Balance", "NUMERIC(18, 2)", True, Nothing, False, False)
                t.AddColumn("Cash_Z_Balance", "NUMERIC(18, 2)", True, Nothing, False, False)
                t.AddColumn("Cash_Balance", "NUMERIC(18, 2)", True, Nothing, False, False)
                t.AddColumn("Cash_Stats", "INT", True, Nothing, False, False)
                t.AddColumn("Cash_Note", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("BRAN_ID", "NUMERIC(18, 0)", True, Nothing, False, False)
                list.Add(t)

                ' 30. MaterialUnits (وحدات قياس الخامات)
                t = New TableDefinition("MaterialUnits", "وحدات قياس الخامات", "Material Units", False)
                t.AddColumn("MaterialUnitID", "INT", False, Nothing, True, True)
                t.AddColumn("MaterialID", "INT", False, Nothing, False, False)
                t.AddColumn("UnitID", "INT", False, Nothing, False, False)
                t.AddColumn("ConversionFactor", "DECIMAL(18, 2)", False, Nothing, False, False)
                t.AddColumn("Barcode", "NVARCHAR(50)", True, Nothing, False, False)
                t.AddColumn("PurchasePrice", "DECIMAL(18, 4)", True, "0.0000", False, False)
                t.AddColumn("Notes", "NVARCHAR(200)", True, Nothing, False, False)
                t.AddColumn("CostPrice", "DECIMAL(18, 2)", False, "0", False, False)
                list.Add(t)

                ' 31. Partners (سجل الشركاء)
                t = New TableDefinition("Partners", "سجل الشركاء", "Partners", False)
                t.AddColumn("Partner_ID", "INT", False, Nothing, True, True)
                t.AddColumn("Partner_Name", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Partner_Type", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Phone", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Address", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Email", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("CompanyName", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Balance", "NUMERIC(18, 2)", True, "0", False, False)
                t.AddColumn("Notes", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("CreatedAt", "DATETIME", True, "getdate()", False, False)
                t.AddColumn("ImagePath", "NVARCHAR(MAX)", True, Nothing, False, False)
                list.Add(t)

                ' 32. PendingInvoices (الفواتير المعلقة والطلبات)
                t = New TableDefinition("PendingInvoices", "الفواتير المعلقة والطلبات", "Pending Invoices", True)
                t.AddColumn("PendingID", "INT", False, Nothing, True, True)
                t.AddColumn("PendingNumber", "NVARCHAR(50)", False, Nothing, False, False)
                t.AddColumn("PendingDate", "DATETIME", False, "getdate()", False, False)
                t.AddColumn("ShiftID", "INT", False, Nothing, False, False)
                t.AddColumn("UserID", "INT", False, Nothing, False, False)
                t.AddColumn("OrderType", "TINYINT", False, "1", False, False)
                t.AddColumn("CustomerID", "INT", True, Nothing, False, False)
                t.AddColumn("CustomerName", "NVARCHAR(150)", True, Nothing, False, False)
                t.AddColumn("TableID", "INT", True, Nothing, False, False)
                t.AddColumn("TableName", "NVARCHAR(100)", True, Nothing, False, False)
                t.AddColumn("DriverID", "INT", True, Nothing, False, False)
                t.AddColumn("DriverName", "NVARCHAR(150)", True, Nothing, False, False)
                t.AddColumn("DeliveryFee", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("InvoiceJSON", "NVARCHAR(MAX)", False, Nothing, False, False)
                t.AddColumn("TotalAmount", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("Notes", "NVARCHAR(500)", True, Nothing, False, False)
                t.AddColumn("IsActive", "BIT", False, "1", False, False)
                t.AddColumn("CreatedAt", "DATETIME", False, "getdate()", False, False)
                list.Add(t)

                ' 33. Permissions (مصفوفة صلاحيات المستخدمين)
                t = New TableDefinition("Permissions", "مصفوفة صلاحيات المستخدمين", "Permissions Matrix", False)
                t.AddColumn("PermissionID", "INT", False, Nothing, True, True)
                t.AddColumn("RoleID", "INT", False, Nothing, False, False)
                t.AddColumn("FormName", "NVARCHAR(100)", False, Nothing, False, False)
                t.AddColumn("CanOpen", "BIT", False, "0", False, False)
                t.AddColumn("CanAdd", "BIT", False, "0", False, False)
                t.AddColumn("CanEdit", "BIT", False, "0", False, False)
                t.AddColumn("CanDelete", "BIT", False, "0", False, False)
                list.Add(t)

                ' 34. Printers (طابعات الكاشير والمطبخ)
                t = New TableDefinition("Printers", "طابعات الكاشير والمطبخ", "Printers", False)
                t.AddColumn("PrinterID", "INT", False, Nothing, True, True)
                t.AddColumn("PrinterName", "NVARCHAR(200)", False, Nothing, False, False)
                t.AddColumn("TargetPrinter", "NVARCHAR(500)", True, Nothing, False, False)
                t.AddColumn("Note", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("IsActive", "BIT", True, "1", False, False)
                t.AddColumn("IsDeleted", "BIT", True, "0", False, False)
                t.AddColumn("PrinterType", "NVARCHAR(50)", True, Nothing, False, False)
                list.Add(t)

                ' 35. ProductAddons (إضافات وخيارات الأصناف)
                t = New TableDefinition("ProductAddons", "إضافات وخيارات الأصناف", "Product Addons", False)
                t.AddColumn("ProductAddonID", "INT", False, Nothing, True, True)
                t.AddColumn("ProductID", "INT", False, Nothing, False, False)
                t.AddColumn("AddonID", "INT", False, Nothing, False, False)
                t.AddColumn("CostPrice", "DECIMAL(18, 2)", False, "0.00", False, False)
                t.AddColumn("SalePrice", "DECIMAL(18, 2)", False, "0.00", False, False)
                t.AddColumn("IsActive", "BIT", False, "1", False, False)
                t.AddColumn("IsDeleted", "BIT", False, "0", False, False)
                t.AddColumn("CreatedAt", "DATETIME2", False, "getdate()", False, False)
                t.AddColumn("SortOrder", "INT", True, Nothing, False, False)
                t.AddColumn("IsDefault", "BIT", True, Nothing, False, False)
                t.AddColumn("AddonName", "NVARCHAR(150)", True, Nothing, False, False)
                t.AddColumn("Price", "DECIMAL(18, 2)", False, "0", False, False)
                list.Add(t)

                ' 36. ProductSizes (أحجام ومقاسات الأصناف)
                t = New TableDefinition("ProductSizes", "أحجام ومقاسات الأصناف", "Product Sizes", False)
                t.AddColumn("ProductSizeID", "INT", False, Nothing, True, True)
                t.AddColumn("ProductID", "INT", True, Nothing, False, False)
                t.AddColumn("SizeID", "INT", True, Nothing, False, False)
                t.AddColumn("CostPrice", "DECIMAL(18, 2)", True, "0.00", False, False)
                t.AddColumn("SalePrice", "DECIMAL(18, 2)", True, "0.00", False, False)
                t.AddColumn("Barcode", "NVARCHAR(100)", True, Nothing, False, False)
                t.AddColumn("ImageBase64", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("IsDefault", "BIT", True, "0", False, False)
                t.AddColumn("SortOrder", "INT", True, "1", False, False)
                t.AddColumn("IsActive", "BIT", True, "1", False, False)
                t.AddColumn("IsDeleted", "BIT", True, "0", False, False)
                t.AddColumn("CreatedAt", "DATETIME2", True, "getdate()", False, False)
                list.Add(t)

                ' 37. ProductUnits (وحدات وأسعار بيع الأصناف)
                t = New TableDefinition("ProductUnits", "وحدات وأسعار بيع الأصناف", "Product Units", False)
                t.AddColumn("ProductUnit_ID", "INT", False, Nothing, True, True)
                t.AddColumn("Product_ID", "INT", True, Nothing, False, False)
                t.AddColumn("Unit_Name", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Unit_Quantity", "DECIMAL(18, 4)", True, Nothing, False, False)
                t.AddColumn("Unit_Order", "INT", True, Nothing, False, False)
                t.AddColumn("Barcode", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Purchase_Price", "DECIMAL(18, 2)", True, Nothing, False, False)
                t.AddColumn("Sale_Price", "DECIMAL(18, 2)", True, Nothing, False, False)
                t.AddColumn("Notes", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("BarcodeImage", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("UnitID", "INT", True, Nothing, False, False)
                t.AddColumn("ProductID", "INT", True, Nothing, False, False)
                t.AddColumn("UnitName", "NVARCHAR(100)", True, Nothing, False, False)
                t.AddColumn("ConversionFactor", "DECIMAL(18, 4)", False, "1", False, False)
                t.AddColumn("SalePrice", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("IsDefault", "BIT", False, "0", False, False)
                list.Add(t)

                ' 38. Products (الأصناف والمنتجات)
                t = New TableDefinition("Products", "الأصناف والمنتجات", "Products", False)
                t.AddColumn("Product_ID", "INT", False, Nothing, True, True)
                t.AddColumn("ProductCode", "NVARCHAR(50)", True, Nothing, False, False)
                t.AddColumn("ProductNameAr", "NVARCHAR(250)", False, Nothing, False, False)
                t.AddColumn("ProductNameEn", "NVARCHAR(250)", True, Nothing, False, False)
                t.AddColumn("Image", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Description", "NVARCHAR(250)", True, Nothing, False, False)
                t.AddColumn("DiscountPercent", "FLOAT", True, Nothing, False, False)
                t.AddColumn("TaxPercent", "FLOAT", True, Nothing, False, False)
                t.AddColumn("IsActive", "BIT", True, Nothing, False, False)
                t.AddColumn("IsDeleted", "BIT", True, "0", False, False)
                t.AddColumn("PreparationTime", "TIME", True, Nothing, False, False)
                t.AddColumn("Notes", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Category_ID", "INT", True, Nothing, False, False)
                t.AddColumn("IsDiscountPercent", "BIT", True, "1", False, False)
                t.AddColumn("IsTaxPercent", "BIT", True, "1", False, False)
                t.AddColumn("ProductID", "INT", True, Nothing, False, False)
                t.AddColumn("CategoryID", "INT", True, Nothing, False, False)
                t.AddColumn("Barcode", "NVARCHAR(100)", True, Nothing, False, False)
                t.AddColumn("ProductName", "NVARCHAR(200)", True, Nothing, False, False)
                t.AddColumn("SalePrice", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("CostPrice", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("Quantity", "DECIMAL(18, 3)", False, "0", False, False)
                t.AddColumn("MinQuantity", "DECIMAL(18, 3)", False, "0", False, False)
                t.AddColumn("Unit", "NVARCHAR(50)", True, Nothing, False, False)
                t.AddColumn("ImageBase64", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("CreatedAt", "DATETIME", False, "getdate()", False, False)
                t.AddColumn("BasePrice", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("Partner_ID", "INT", True, Nothing, False, False)
                t.AddColumn("IsDirect", "BIT", True, "1", False, False)
                list.Add(t)

                ' 39. PurchaseDetails (تفاصيل فواتير المشتريات)
                t = New TableDefinition("PurchaseDetails", "تفاصيل فواتير المشتريات", "Purchase Details", True)
                t.AddColumn("DetailID", "INT", False, Nothing, True, True)
                t.AddColumn("PurchaseID", "INT", False, Nothing, False, False)
                t.AddColumn("MaterialID", "INT", False, Nothing, False, False)
                t.AddColumn("UnitID", "INT", False, Nothing, False, False)
                t.AddColumn("Quantity", "DECIMAL(18, 4)", False, Nothing, False, False)
                t.AddColumn("ConversionFactor", "DECIMAL(18, 4)", False, "1.0000", False, False)
                t.AddColumn("ActualBaseQuantity", "DECIMAL(37, 8)", True, Nothing, False, False)
                t.AddColumn("UnitPrice", "DECIMAL(18, 4)", False, Nothing, False, False)
                t.AddColumn("BaseUnitCost", "DECIMAL(18, 6)", False, "0.000000", False, False)
                t.AddColumn("TotalPrice", "DECIMAL(37, 8)", True, Nothing, False, False)
                t.AddColumn("ProductID", "INT", True, Nothing, False, False)
                t.AddColumn("Total", "DECIMAL(18, 2)", False, "0", False, False)
                list.Add(t)

                ' 40. PurchaseHeaders (رؤوس فواتير المشتريات)
                t = New TableDefinition("PurchaseHeaders", "رؤوس فواتير المشتريات", "Purchase Headers", True)
                t.AddColumn("PurchaseID", "INT", False, Nothing, True, True)
                t.AddColumn("InvoiceNumber", "NVARCHAR(50)", False, Nothing, False, False)
                t.AddColumn("SupplierID", "INT", False, Nothing, False, False)
                t.AddColumn("StoreID", "INT", False, Nothing, False, False)
                t.AddColumn("BranchID", "INT", True, Nothing, False, False)
                t.AddColumn("PurchaseDate", "DATETIME", False, "getdate()", False, False)
                t.AddColumn("TotalAmount", "DECIMAL(18, 2)", False, "0.00", False, False)
                t.AddColumn("Discount", "DECIMAL(18, 2)", False, "0.00", False, False)
                t.AddColumn("NetTotal", "DECIMAL(18, 2)", False, "0.00", False, False)
                t.AddColumn("PaidAmount", "DECIMAL(18, 2)", False, "0.00", False, False)
                t.AddColumn("RemainingAmount", "DECIMAL(18, 2)", False, "0.00", False, False)
                t.AddColumn("PaymentType", "NVARCHAR(20)", False, "'CASH'", False, False)
                t.AddColumn("TreasuryID", "INT", True, Nothing, False, False)
                t.AddColumn("Notes", "NVARCHAR(250)", True, Nothing, False, False)
                t.AddColumn("UserID", "INT", False, Nothing, False, False)
                t.AddColumn("CreatedAt", "DATETIME", False, "getdate()", False, False)
                t.AddColumn("IsDeleted", "BIT", False, "0", False, False)
                list.Add(t)



                ' 44. RawMaterials (المواد الخام ومكونات التصنيع)
                t = New TableDefinition("RawMaterials", "المواد الخام ومكونات التصنيع", "Raw Materials", False)
                t.AddColumn("MaterialID", "INT", False, Nothing, True, True)
                t.AddColumn("MaterialBarcode", "NVARCHAR(100)", True, Nothing, False, False)
                t.AddColumn("MaterialName", "NVARCHAR(150)", True, Nothing, False, False)
                t.AddColumn("UnitID", "INT", True, Nothing, False, False)
                t.AddColumn("CostPrice", "DECIMAL(18, 4)", True, "0.0000", False, False)
                t.AddColumn("CreatedAt", "DATETIME", True, "getdate()", False, False)
                t.AddColumn("IsActive", "BIT", True, "1", False, False)
                t.AddColumn("IsDeleted", "BIT", True, Nothing, False, False)
                list.Add(t)

                ' 45. Recipes (وصفات ومكونات الأصناف (BOM))
                t = New TableDefinition("Recipes", "وصفات ومكونات الأصناف (BOM)", "Recipes", False)
                t.AddColumn("RecipeID", "INT", False, Nothing, True, True)
                t.AddColumn("ProductID", "INT", False, Nothing, False, False)
                t.AddColumn("SizeID", "INT", True, Nothing, False, False)
                t.AddColumn("AddonID", "INT", True, Nothing, False, False)
                t.AddColumn("MaterialID", "INT", True, Nothing, False, False)
                t.AddColumn("Quantity", "DECIMAL(18, 4)", True, Nothing, False, False)
                t.AddColumn("Notes", "NVARCHAR(150)", True, Nothing, False, False)
                t.AddColumn("UnitID", "INT", True, Nothing, False, False)
                list.Add(t)

                ' 46. RestaurantSections (صالات وأقسام المطعم)
                t = New TableDefinition("RestaurantSections", "صالات وأقسام المطعم", "Restaurant Sections", False)
                t.AddColumn("SectionID", "INT", False, Nothing, True, True)
                t.AddColumn("SectionCode", "NVARCHAR(20)", True, Nothing, False, False)
                t.AddColumn("SectionName", "NVARCHAR(100)", False, Nothing, False, False)
                t.AddColumn("TablesCount", "INT", False, "0", False, False)
                t.AddColumn("Notes", "NVARCHAR(250)", True, Nothing, False, False)
                t.AddColumn("IsActive", "BIT", False, "1", False, False)
                t.AddColumn("IsDeleted", "BIT", False, "0", False, False)
                t.AddColumn("CreatedAt", "DATETIME2", False, "getdate()", False, False)
                list.Add(t)

                ' 47. RestaurantTables (طاولات وصالات الجلوس)
                t = New TableDefinition("RestaurantTables", "طاولات وصالات الجلوس", "Restaurant Tables", False)
                t.AddColumn("TableID", "INT", False, Nothing, True, True)
                t.AddColumn("TableNumber", "NVARCHAR(20)", False, Nothing, False, False)
                t.AddColumn("TableName", "NVARCHAR(100)", True, Nothing, False, False)
                t.AddColumn("SectionID", "INT", False, Nothing, False, False)
                t.AddColumn("ChairsCount", "INT", False, "4", False, False)
                t.AddColumn("TableStatus", "TINYINT", False, "1", False, False)
                t.AddColumn("Notes", "NVARCHAR(250)", True, Nothing, False, False)
                t.AddColumn("IsActive", "BIT", False, "1", False, False)
                t.AddColumn("IsDeleted", "BIT", False, "0", False, False)
                t.AddColumn("CreatedAt", "DATETIME2", False, "getdate()", False, False)
                t.AddColumn("Capacity", "INT", False, "4", False, False)
                t.AddColumn("Status", "NVARCHAR(50)", False, "'Available'", False, False)
                list.Add(t)

                ' 48. Roles (الأدوار والصلاحيات)
                t = New TableDefinition("Roles", "الأدوار والصلاحيات", "Roles", False)
                t.AddColumn("RoleID", "INT", False, Nothing, True, True)
                t.AddColumn("RoleName", "NVARCHAR(100)", False, Nothing, False, False)
                t.AddColumn("Description", "NVARCHAR(250)", True, Nothing, False, False)
                t.AddColumn("IsActive", "BIT", False, "1", False, False)
                list.Add(t)

                ' 49. SalaryPayments (صرف الرواتب والسلف)
                t = New TableDefinition("SalaryPayments", "صرف الرواتب والسلف", "Salary Payments", True)
                t.AddColumn("PaymentID", "INT", False, Nothing, True, True)
                t.AddColumn("PaymentNumber", "NVARCHAR(30)", False, Nothing, False, False)
                t.AddColumn("EmployeeID", "INT", False, Nothing, False, False)
                t.AddColumn("TreasuryID", "INT", False, Nothing, False, False)
                t.AddColumn("ShiftID", "INT", True, Nothing, False, False)
                t.AddColumn("PaymentDate", "DATETIME", False, "getdate()", False, False)
                t.AddColumn("SalaryMonth", "INT", False, Nothing, False, False)
                t.AddColumn("SalaryYear", "INT", False, Nothing, False, False)
                t.AddColumn("BasicSalary", "DECIMAL(18, 2)", False, "0.00", False, False)
                t.AddColumn("Allowances", "DECIMAL(18, 2)", False, "0.00", False, False)
                t.AddColumn("Deductions", "DECIMAL(18, 2)", False, "0.00", False, False)
                t.AddColumn("Advances", "DECIMAL(18, 2)", False, "0.00", False, False)
                t.AddColumn("NetSalary", "DECIMAL(18, 2)", False, Nothing, False, False)
                t.AddColumn("Notes", "NVARCHAR(250)", True, Nothing, False, False)
                t.AddColumn("PaidByUserID", "INT", False, Nothing, False, False)
                t.AddColumn("CreatedAt", "DATETIME", False, "getdate()", False, False)
                list.Add(t)

                ' 50. SalarySystems (أنظمة احتساب الرواتب)
                t = New TableDefinition("SalarySystems", "أنظمة احتساب الرواتب", "Salary Systems", False)
                t.AddColumn("SalarySystemID", "INT", False, Nothing, True, True)
                t.AddColumn("SalarySystemCode", "NVARCHAR(20)", True, Nothing, False, False)
                t.AddColumn("SalarySystemName", "NVARCHAR(100)", False, Nothing, False, False)
                t.AddColumn("PaymentDays", "INT", True, Nothing, False, False)
                t.AddColumn("Notes", "NVARCHAR(500)", True, Nothing, False, False)
                t.AddColumn("IsActive", "BIT", False, "1", False, False)
                t.AddColumn("IsDeleted", "BIT", False, "0", False, False)
                t.AddColumn("CreatedAt", "DATETIME2", False, "getdate()", False, False)
                t.AddColumn("CreatedBy", "INT", True, Nothing, False, False)
                list.Add(t)

                ' 51. Sales (المبيعات السريعة (توافقي))
                t = New TableDefinition("Sales", "المبيعات السريعة (توافقي)", "Sales (Legacy)", True)
                t.AddColumn("SaleID", "INT", False, Nothing, True, True)
                t.AddColumn("InvoiceNo", "NVARCHAR(50)", True, Nothing, False, False)
                t.AddColumn("SaleDate", "DATETIME", False, "getdate()", False, False)
                t.AddColumn("CustomerID", "INT", True, Nothing, False, False)
                t.AddColumn("UserID", "INT", False, Nothing, False, False)
                t.AddColumn("ShiftID", "INT", True, Nothing, False, False)
                t.AddColumn("SubTotal", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("Discount", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("Tax", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("Total", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("Paid", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("Remaining", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("PaymentType", "NVARCHAR(50)", False, "'Cash'", False, False)
                t.AddColumn("Status", "NVARCHAR(50)", False, "'Completed'", False, False)
                t.AddColumn("Notes", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("IsDeleted", "BIT", False, "0", False, False)
                list.Add(t)

                ' 52. SalesDetails (تفاصيل فواتير المبيعات)
                t = New TableDefinition("SalesDetails", "تفاصيل فواتير المبيعات", "Sales Details", True)
                t.AddColumn("Detail_ID", "INT", False, Nothing, True, True)
                t.AddColumn("Invoice_ID", "INT", True, Nothing, False, False)
                t.AddColumn("Product_ID", "INT", True, Nothing, False, False)
                t.AddColumn("Product_Name", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("ProductUnit_ID", "INT", True, Nothing, False, False)
                t.AddColumn("ProductUnit_Name", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Quantity_Sold", "DECIMAL(18, 2)", True, Nothing, False, False)
                t.AddColumn("Sale_Price_Per_Unit", "DECIMAL(18, 2)", True, Nothing, False, False)
                t.AddColumn("Total_Line_Amount", "DECIMAL(18, 2)", True, Nothing, False, False)
                t.AddColumn("Profit", "DECIMAL(18, 2)", True, Nothing, False, False)
                t.AddColumn("Purchase_Price_At_Sale", "DECIMAL(18, 2)", True, Nothing, False, False)
                t.AddColumn("DetailID", "INT", True, Nothing, False, False)
                t.AddColumn("SaleID", "INT", True, Nothing, False, False)
                t.AddColumn("ProductID", "INT", True, Nothing, False, False)
                t.AddColumn("Quantity", "DECIMAL(18, 3)", False, "1", False, False)
                t.AddColumn("UnitPrice", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("CostPrice", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("Discount", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("Total", "DECIMAL(18, 2)", False, "0", False, False)
                list.Add(t)

                ' 53. SalesHeader (رأس فواتير المبيعات (توافقي))
                t = New TableDefinition("SalesHeader", "رأس فواتير المبيعات (توافقي)", "Sales Header (Legacy)", True)
                t.AddColumn("Invoice_ID", "INT", False, Nothing, True, True)
                t.AddColumn("Invoice_Date", "DATETIME", True, "getdate()", False, False)
                t.AddColumn("Customer_ID", "INT", True, Nothing, False, False)
                t.AddColumn("User_ID", "INT", True, Nothing, False, False)
                t.AddColumn("User_Name", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Net_Amount", "DECIMAL(18, 2)", True, Nothing, False, False)
                t.AddColumn("Discount_Value", "DECIMAL(18, 2)", True, "0.00", False, False)
                t.AddColumn("Total_Amount", "DECIMAL(18, 2)", True, Nothing, False, False)
                t.AddColumn("Payment_Method", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Amount_Paid", "DECIMAL(18, 2)", True, Nothing, False, False)
                t.AddColumn("Remaining", "DECIMAL(18, 2)", True, Nothing, False, False)
                t.AddColumn("Total_Profit", "DECIMAL(18, 2)", True, Nothing, False, False)
                t.AddColumn("Notes", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Invoice_type", "NVARCHAR(50)", True, Nothing, False, False)
                t.AddColumn("Invoice_Code", "INT", True, Nothing, False, False)
                t.AddColumn("TreasuryID", "INT", True, Nothing, False, False)
                t.AddColumn("PreviousBalance", "DECIMAL(18, 2)", True, Nothing, False, False)
                list.Add(t)

                ' 54. SalesInvoiceDetails (تفاصيل أصناف الفاتورة)
                t = New TableDefinition("SalesInvoiceDetails", "تفاصيل أصناف الفاتورة", "Sales Invoice Details", True)
                t.AddColumn("DetailID", "INT", False, Nothing, True, True)
                t.AddColumn("InvoiceID", "INT", False, Nothing, False, False)
                t.AddColumn("ProductID", "INT", False, Nothing, False, False)
                t.AddColumn("ProductName", "NVARCHAR(250)", False, Nothing, False, False)
                t.AddColumn("SizeName", "NVARCHAR(100)", True, Nothing, False, False)
                t.AddColumn("AddonsText", "NVARCHAR(500)", True, Nothing, False, False)
                t.AddColumn("UnitPrice", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("Quantity", "INT", False, "1", False, False)
                t.AddColumn("TotalPrice", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("Notes", "NVARCHAR(250)", True, Nothing, False, False)
                t.AddColumn("CostPrice", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("Discount", "DECIMAL(18, 2)", False, "0", False, False)
                ' v1.4.0: تُحفظ معرّفات الحجم والإضافات لتُخصم وتُرجَع وصفات المخزون بدقة
                ' (كانت تُهمل فتُخصم الوصفة الأساسية فقط، ويستحيل إرجاع وصفة الحجم/الإضافة)
                t.AddColumn("SizeID", "INT", True, Nothing, False, False)
                t.AddColumn("AddonIDs", "NVARCHAR(200)", True, Nothing, False, False)
                list.Add(t)

                ' 55. SalesInvoices (فواتير المبيعات الحديثة)
                t = New TableDefinition("SalesInvoices", "فواتير المبيعات الحديثة", "Sales Invoices", True)
                t.AddColumn("InvoiceID", "INT", False, Nothing, True, True)
                t.AddColumn("InvoiceNumber", "NVARCHAR(50)", False, Nothing, False, False)
                t.AddColumn("InvoiceDate", "DATETIME", False, "getdate()", False, False)
                t.AddColumn("OrderType", "TINYINT", False, "1", False, False)
                t.AddColumn("ShiftID", "INT", False, Nothing, False, False)
                t.AddColumn("UserID", "INT", False, Nothing, False, False)
                t.AddColumn("CustomerID", "INT", True, Nothing, False, False)
                t.AddColumn("TableID", "INT", True, Nothing, False, False)
                t.AddColumn("DriverID", "INT", True, Nothing, False, False)
                t.AddColumn("DeliveryFee", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("DineInServiceFee", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("TotalBeforeDiscount", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("DiscountAmount", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("NetTotal", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("PaidAmount", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("RemainingAmount", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("IsCredit", "BIT", False, "0", False, False)
                t.AddColumn("TreasuryID", "INT", True, Nothing, False, False)
                t.AddColumn("Notes", "NVARCHAR(500)", True, Nothing, False, False)
                t.AddColumn("IsActive", "BIT", False, "1", False, False)
                t.AddColumn("IsDeleted", "BIT", False, "0", False, False)
                t.AddColumn("CreatedAt", "DATETIME", False, "getdate()", False, False)
                t.AddColumn("BranchID", "INT", True, Nothing, False, False)
                t.AddColumn("StoreID", "INT", True, Nothing, False, False)
                t.AddColumn("SubTotal", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("Discount", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("Tax", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("PaymentType", "NVARCHAR(50)", False, "N'نقدي'", False, False)
                ' v1.4.0: ربط فاتورة المرتجع بالفاتورة الأصلية — يمنع إرجاع نفس الفاتورة أكثر من مرة
                ' (سابقاً كان الربط الوحيد هو نص في Notes، فكان الاسترداد المتكرر ممكناً)
                t.AddColumn("OriginalInvoiceID", "INT", True, Nothing, False, False)
                list.Add(t)

                ' 56. Settings (إعدادات النظام العامة)
                t = New TableDefinition("Settings", "إعدادات النظام العامة", "General Settings", False)
                t.AddColumn("SettingKey", "NVARCHAR(100)", False, Nothing, False, True)
                t.AddColumn("SettingValue", "NVARCHAR(500)", True, Nothing, False, False)
                list.Add(t)

                ' 57. Shifts (ورديات العمل ونقاط البيع)
                t = New TableDefinition("Shifts", "ورديات العمل ونقاط البيع", "Shifts", True)
                t.AddColumn("ShiftID", "INT", False, Nothing, True, True)
                t.AddColumn("ShiftNumber", "NVARCHAR(30)", False, Nothing, False, False)
                t.AddColumn("BranchID", "INT", True, Nothing, False, False)
                t.AddColumn("UserID", "INT", False, Nothing, False, False)
                t.AddColumn("OpenDateTime", "DATETIME2", False, "getdate()", False, False)
                t.AddColumn("CloseDateTime", "DATETIME2", True, Nothing, False, False)
                t.AddColumn("OpeningCash", "DECIMAL(18, 2)", False, "0.00", False, False)
                t.AddColumn("ClosingCash", "DECIMAL(18, 2)", True, Nothing, False, False)
                t.AddColumn("ExpectedCash", "DECIMAL(18, 2)", True, Nothing, False, False)
                t.AddColumn("CashDifference", "DECIMAL(18, 2)", True, Nothing, False, False)
                t.AddColumn("TotalSales", "DECIMAL(18, 2)", False, "0.00", False, False)
                t.AddColumn("TotalVisaSales", "DECIMAL(18, 2)", False, "0.00", False, False)
                t.AddColumn("TotalRefunds", "DECIMAL(18, 2)", False, "0.00", False, False)
                t.AddColumn("TotalPurchases", "DECIMAL(18, 2)", False, "0.00", False, False)
                t.AddColumn("TotalPurchaseRefunds", "DECIMAL(18, 2)", False, "0.00", False, False)
                t.AddColumn("TotalExpenses", "DECIMAL(18, 2)", False, "0.00", False, False)
                t.AddColumn("TotalIncomes", "DECIMAL(18, 2)", False, "0.00", False, False)
                t.AddColumn("TotalOrders", "INT", False, "0", False, False)
                t.AddColumn("Status", "TINYINT", False, "1", False, False)
                t.AddColumn("Notes", "NVARCHAR(500)", True, Nothing, False, False)
                t.AddColumn("ClosedByUserID", "INT", True, Nothing, False, False)
                t.AddColumn("IsActive", "BIT", False, "1", False, False)
                t.AddColumn("IsDeleted", "BIT", False, "0", False, False)
                t.AddColumn("WorkShiftID", "INT", True, Nothing, False, False)
                t.AddColumn("StartTime", "DATETIME", False, "getdate()", False, False)
                t.AddColumn("EndTime", "DATETIME", True, Nothing, False, False)
                t.AddColumn("StartCash", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("EndCash", "DECIMAL(18, 2)", True, Nothing, False, False)
                t.AddColumn("ActualCash", "DECIMAL(18, 2)", True, Nothing, False, False)
                t.AddColumn("Difference", "DECIMAL(18, 2)", True, Nothing, False, False)
                t.AddColumn("CreatedAt", "DATETIME", False, "getdate()", False, False)
                t.AddColumn("TreasuryID", "INT", True, Nothing, False, False)
                list.Add(t)

                ' 58. Sizes (الأحجام والمقاسات العامة)
                t = New TableDefinition("Sizes", "الأحجام والمقاسات العامة", "Sizes", False)
                t.AddColumn("SizeID", "INT", False, Nothing, True, True)
                t.AddColumn("SizeCode", "NVARCHAR(20)", True, Nothing, False, False)
                t.AddColumn("SizeNameAr", "NVARCHAR(100)", False, Nothing, False, False)
                t.AddColumn("SizeNameEn", "NVARCHAR(100)", True, Nothing, False, False)
                t.AddColumn("Notes", "NVARCHAR(250)", True, Nothing, False, False)
                t.AddColumn("IsActive", "BIT", False, "1", False, False)
                t.AddColumn("IsDeleted", "BIT", False, "0", False, False)
                t.AddColumn("CreatedAt", "DATETIME2", False, "getdate()", False, False)
                list.Add(t)

                ' 59. Stock (أرصدة المخزون للمنتجات)
                t = New TableDefinition("Stock", "أرصدة المخزون للمنتجات", "Product Stock", False)
                t.AddColumn("Stock_ID", "INT", False, Nothing, True, True)
                t.AddColumn("Product_ID", "INT", False, Nothing, False, False)
                t.AddColumn("Quantity_OnHand", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("Min_Quantity", "DECIMAL(18, 2)", True, Nothing, False, False)
                t.AddColumn("Max_Quantity", "DECIMAL(18, 2)", True, Nothing, False, False)
                t.AddColumn("Last_Update", "DATETIME", True, "getdate()", False, False)
                t.AddColumn("Unit_Name", "NVARCHAR(50)", True, Nothing, False, False)
                t.AddColumn("Barcode", "NVARCHAR(100)", True, Nothing, False, False)
                t.AddColumn("Purchase_Price", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("Sale_Price", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("Notes", "NVARCHAR(MAX)", True, Nothing, False, False)
                list.Add(t)

                ' 60. StockMovements (تحويلات وحركات المخازن)
                t = New TableDefinition("StockMovements", "تحويلات وحركات المخازن", "Stock Movements", True)
                t.AddColumn("MovementID", "INT", False, Nothing, True, True)
                t.AddColumn("StoreID", "INT", False, Nothing, False, False)
                t.AddColumn("MaterialID", "INT", False, Nothing, False, False)
                t.AddColumn("MovementType", "NVARCHAR(50)", False, Nothing, False, False)
                t.AddColumn("Quantity", "DECIMAL(18, 3)", False, Nothing, False, False)
                t.AddColumn("ReferenceID", "INT", True, Nothing, False, False)
                t.AddColumn("CreatedDate", "DATETIME", True, "getdate()", False, False)
                list.Add(t)

                ' 61. StockTransactions (حركات المخزون التفصيلية)
                t = New TableDefinition("StockTransactions", "حركات المخزون التفصيلية", "Stock Transactions", True)
                t.AddColumn("Transaction_ID", "INT", False, Nothing, True, True)
                t.AddColumn("Product_ID", "INT", False, Nothing, False, False)
                t.AddColumn("ProductUnit_ID", "INT", False, Nothing, False, False)
                t.AddColumn("Quantity", "NUMERIC(18, 0)", False, Nothing, False, False)
                t.AddColumn("Base_Quantity", "NVARCHAR(MAX)", True, "getdate()", False, False)
                t.AddColumn("Transaction_Type", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Transaction_Date", "DATE", True, Nothing, False, False)
                t.AddColumn("Reference_No", "INT", True, Nothing, False, False)
                t.AddColumn("Notes", "NVARCHAR(MAX)", True, Nothing, False, False)
                list.Add(t)

                ' 62. StoreStock (أرصدة الخامات في المخازن)
                t = New TableDefinition("StoreStock", "أرصدة الخامات في المخازن", "Store Stock", False)
                t.AddColumn("StockID", "INT", False, Nothing, True, True)
                t.AddColumn("StoreID", "INT", False, Nothing, False, False)
                t.AddColumn("MaterialID", "INT", False, Nothing, False, False)
                t.AddColumn("CurrentStock", "DECIMAL(18, 3)", True, "0.000", False, False)
                t.AddColumn("MinStock", "DECIMAL(18, 6)", True, "0", False, False)
                t.AddColumn("MaxStock", "DECIMAL(18, 6)", True, Nothing, False, False)
                t.AddColumn("MinUnitID", "INT", True, Nothing, False, False)
                t.AddColumn("MaxUnitID", "INT", True, Nothing, False, False)
                list.Add(t)

                ' 63. Stores (المستودعات والمخازن)
                t = New TableDefinition("Stores", "المستودعات والمخازن", "Stores", False)
                t.AddColumn("StoreID", "INT", False, Nothing, True, True)
                t.AddColumn("StoreName", "NVARCHAR(250)", False, Nothing, False, False)
                t.AddColumn("IsDefault", "BIT", True, "0", False, False)
                t.AddColumn("IsActive", "BIT", True, "1", False, False)
                t.AddColumn("IsDeleted", "BIT", True, "0", False, False)
                t.AddColumn("StoreCode", "NVARCHAR(50)", True, Nothing, False, False)
                list.Add(t)

                ' 64. SupplierTransactions (حركات وحسابات الموردين)
                t = New TableDefinition("SupplierTransactions", "حركات وحسابات الموردين", "Supplier Transactions", True)
                t.AddColumn("TransactionID", "INT", False, Nothing, True, True)
                t.AddColumn("SupplierID", "INT", False, Nothing, False, False)
                t.AddColumn("TransactionType", "NVARCHAR(50)", False, Nothing, False, False)
                t.AddColumn("ReferenceNo", "NVARCHAR(50)", True, Nothing, False, False)
                t.AddColumn("Debit", "DECIMAL(18, 2)", False, "0.00", False, False)
                t.AddColumn("Credit", "DECIMAL(18, 2)", False, "0.00", False, False)
                t.AddColumn("BalanceBefore", "DECIMAL(18, 2)", True, Nothing, False, False)
                t.AddColumn("BalanceAfter", "DECIMAL(18, 2)", False, Nothing, False, False)
                t.AddColumn("TransactionDate", "DATETIME", False, "getdate()", False, False)
                t.AddColumn("TreasuryID", "INT", True, Nothing, False, False)
                t.AddColumn("Notes", "NVARCHAR(250)", True, Nothing, False, False)
                t.AddColumn("UserID", "INT", False, Nothing, False, False)
                t.AddColumn("SuppliersID", "INT", True, Nothing, False, False)
                t.AddColumn("Amount", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("PaymentMethod", "NVARCHAR(30)", True, Nothing, False, False)
                list.Add(t)

                ' 65. Suppliers (سجل الموردين والشركات)
                t = New TableDefinition("Suppliers", "سجل الموردين والشركات", "Suppliers", False)
                t.AddColumn("SupplierID", "INT", False, Nothing, True, True)
                t.AddColumn("SupplierCode", "NVARCHAR(30)", False, Nothing, False, False)
                t.AddColumn("SupplierName", "NVARCHAR(150)", False, Nothing, False, False)
                t.AddColumn("Phone", "NVARCHAR(30)", True, Nothing, False, False)
                t.AddColumn("Address", "NVARCHAR(250)", True, Nothing, False, False)
                t.AddColumn("CurrentBalance", "DECIMAL(18, 2)", False, "0.00", False, False)
                t.AddColumn("Notes", "NVARCHAR(250)", True, Nothing, False, False)
                t.AddColumn("IsActive", "BIT", False, "1", False, False)
                t.AddColumn("IsDeleted", "BIT", False, "0", False, False)
                t.AddColumn("CreatedAt", "DATETIME", False, "getdate()", False, False)
                t.AddColumn("Balance", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("SuppliersID", "INT", True, Nothing, False, False)
                t.AddColumn("SuppliersCode", "NVARCHAR(50)", True, Nothing, False, False)
                t.AddColumn("SuppliersName", "NVARCHAR(150)", True, Nothing, False, False)
                t.AddColumn("Companyname", "NVARCHAR(150)", True, Nothing, False, False)
                t.AddColumn("OpeningBalance", "DECIMAL(18, 2)", False, "0.00", False, False)
                list.Add(t)

                ' 66. TableReservations (حجوزات الطاولات والعرابين)
                t = New TableDefinition("TableReservations", "حجوزات الطاولات والعرابين", "Table Reservations", True)
                t.AddColumn("ReservationID", "INT", False, Nothing, True, True)
                t.AddColumn("ReservationNumber", "NVARCHAR(50)", False, Nothing, False, False)
                t.AddColumn("TableID", "INT", False, Nothing, False, False)
                t.AddColumn("TableName", "NVARCHAR(100)", True, Nothing, False, False)
                t.AddColumn("CustomerName", "NVARCHAR(150)", False, Nothing, False, False)
                t.AddColumn("CustomerPhone", "NVARCHAR(50)", False, Nothing, False, False)
                t.AddColumn("GuestCount", "INT", False, "2", False, False)
                t.AddColumn("ReservationDateTime", "DATETIME", False, Nothing, False, False)
                t.AddColumn("DepositAmount", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("TreasuryID", "INT", True, Nothing, False, False)
                t.AddColumn("Status", "TINYINT", False, "1", False, False)
                t.AddColumn("Notes", "NVARCHAR(500)", True, Nothing, False, False)
                t.AddColumn("CreatedAt", "DATETIME", False, "getdate()", False, False)
                t.AddColumn("CreatedByUserID", "INT", False, "1", False, False)
                list.Add(t)

                ' 67. TheScale (ميزان الباركود الإلكتروني)
                t = New TableDefinition("TheScale", "ميزان الباركود الإلكتروني", "The Scale", False)
                t.AddColumn("ID", "INT", False, Nothing, True, True)
                t.AddColumn("Code", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Name", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("Price", "DECIMAL(18, 2)", True, Nothing, False, False)
                t.AddColumn("Purchase_Price", "DECIMAL(18, 2)", True, Nothing, False, False)
                list.Add(t)

                ' 68. Tratde_Type_TBL (أنواع المعاملات التجارية)
                t = New TableDefinition("Tratde_Type_TBL", "أنواع المعاملات التجارية", "Trade Types", False)
                t.AddColumn("Trd_ID", "NUMERIC(18, 0)", False, Nothing, False, True)
                t.AddColumn("Trd_Code", "NUMERIC(18, 0)", True, Nothing, False, False)
                t.AddColumn("Trd_Type", "VARBINARY(50)", True, Nothing, False, False)
                t.AddColumn("Trd_State", "BIT", True, Nothing, False, False)
                t.AddColumn("Trd_Note", "VARCHAR(MAX)", True, Nothing, False, False)
                list.Add(t)

                ' 69. Treasury (الخزائن ونقاط النقدية)
                t = New TableDefinition("Treasury", "الخزائن ونقاط النقدية", "Treasuries", False)
                t.AddColumn("TreasuryID", "INT", False, Nothing, True, True)
                t.AddColumn("TreasuryCode", "NVARCHAR(20)", False, Nothing, False, False)
                t.AddColumn("TreasuryNameAr", "NVARCHAR(100)", False, Nothing, False, False)
                t.AddColumn("Description", "NVARCHAR(500)", True, Nothing, False, False)
                t.AddColumn("OpeningBalance", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("CurrentBalance", "DECIMAL(18, 2)", False, "0", False, False)
                t.AddColumn("IsDefault", "BIT", False, "0", False, False)
                t.AddColumn("IsActive", "BIT", False, "1", False, False)
                t.AddColumn("CreatedDate", "DATETIME", False, "getdate()", False, False)
                t.AddColumn("ModifiedDate", "DATETIME", True, Nothing, False, False)
                t.AddColumn("IsDeleted", "BIT", False, "0", False, False)
                t.AddColumn("TreasuryName", "NVARCHAR(100)", True, Nothing, False, False)
                t.AddColumn("Balance", "DECIMAL(18, 2)", False, "0", False, False)
                list.Add(t)

                ' 70. TreasuryTransactions (حركات وسجلات الخزينة)
                t = New TableDefinition("TreasuryTransactions", "حركات وسجلات الخزينة", "Treasury Transactions", True)
                t.AddColumn("TransactionID", "INT", False, Nothing, True, True)
                t.AddColumn("TreasuryID", "INT", False, Nothing, False, False)
                t.AddColumn("TransactionDate", "DATETIME", False, "getdate()", False, False)
                t.AddColumn("TransactionType", "INT", False, Nothing, False, False)
                t.AddColumn("ReferenceID", "INT", True, Nothing, False, False)
                t.AddColumn("ReferenceNo", "NVARCHAR(50)", True, Nothing, False, False)
                t.AddColumn("Amount", "DECIMAL(18, 2)", False, Nothing, False, False)
                t.AddColumn("IsDeposit", "BIT", False, Nothing, False, False)
                t.AddColumn("Notes", "NVARCHAR(500)", True, Nothing, False, False)
                t.AddColumn("UserID", "INT", True, Nothing, False, False)
                t.AddColumn("CreatedDate", "DATETIME", False, "getdate()", False, False)
                t.AddColumn("ShiftID", "INT", True, Nothing, False, False)
                t.AddColumn("RelatedID", "INT", True, Nothing, False, False)
                list.Add(t)

                ' 71. Units (الوحدات الأساسية للقياس)
                t = New TableDefinition("Units", "الوحدات الأساسية للقياس", "Base Units", False)
                t.AddColumn("UnitID", "INT", False, Nothing, True, True)
                t.AddColumn("UnitCode", "NVARCHAR(50)", True, Nothing, False, False)
                t.AddColumn("UnitName", "NVARCHAR(50)", False, Nothing, False, False)
                t.AddColumn("IsActive", "BIT", True, "1", False, False)
                t.AddColumn("IsDeleted", "BIT", True, "0", False, False)
                list.Add(t)

                ' 72. Users (المستخدمين (توافقي))
                t = New TableDefinition("Users", "المستخدمين (توافقي)", "Users (Legacy)", False)
                t.AddColumn("UserID", "INT", False, Nothing, True, True)
                t.AddColumn("Username", "NVARCHAR(100)", False, Nothing, False, False)
                t.AddColumn("Password", "NVARCHAR(250)", False, Nothing, False, False)
                t.AddColumn("FullName", "NVARCHAR(150)", True, Nothing, False, False)
                t.AddColumn("RoleID", "INT", True, Nothing, False, False)
                t.AddColumn("UserRole", "NVARCHAR(50)", True, Nothing, False, False)
                t.AddColumn("Phone", "NVARCHAR(50)", True, Nothing, False, False)
                t.AddColumn("IsActive", "BIT", False, "1", False, False)
                t.AddColumn("CreatedAt", "DATETIME", False, "getdate()", False, False)
                t.AddColumn("IsDeleted", "BIT", False, "0", False, False)
                list.Add(t)

                ' 73. Users_TBL (سجل المستخدمين والموظفين)
                t = New TableDefinition("Users_TBL", "سجل المستخدمين والموظفين", "Users Table", False)
                t.AddColumn("User_ID", "INT", False, Nothing, True, True)
                t.AddColumn("User_Code", "NVARCHAR(250)", True, Nothing, False, False)
                t.AddColumn("User_Name", "NVARCHAR(250)", True, Nothing, False, False)
                t.AddColumn("User_username", "NVARCHAR(250)", True, Nothing, False, False)
                t.AddColumn("User_password", "NVARCHAR(250)", True, Nothing, False, False)
                t.AddColumn("User_Stats", "BIT", True, Nothing, False, False)
                t.AddColumn("User_Role", "NVARCHAR(200)", True, Nothing, False, False)
                t.AddColumn("User_Note", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("RoleID", "INT", True, Nothing, False, False)
                t.AddColumn("UserBarcode", "NVARCHAR(250)", True, Nothing, False, False)
                t.AddColumn("UserPhotobase64", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("IsActive", "BIT", True, "1", False, False)
                t.AddColumn("IsDeleted", "BIT", True, "0", False, False)
                t.AddColumn("EmployeeID", "INT", True, Nothing, False, False)
                t.AddColumn("User_photo_path", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("User_Barcode_path", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("CreatedAt", "DATETIME", False, "getdate()", False, False)
                list.Add(t)

                ' 74. WorkShifts (فترات ومواعيد العمل)
                t = New TableDefinition("WorkShifts", "فترات ومواعيد العمل", "Work Shifts", False)
                t.AddColumn("WorkShiftID", "INT", False, Nothing, True, True)
                t.AddColumn("WorkShiftCode", "NVARCHAR(20)", True, Nothing, False, False)
                t.AddColumn("WorkShiftName", "NVARCHAR(100)", False, Nothing, False, False)
                t.AddColumn("StartTime", "TIME", False, Nothing, False, False)
                t.AddColumn("EndTime", "TIME", False, Nothing, False, False)
                t.AddColumn("Notes", "NVARCHAR(250)", True, Nothing, False, False)
                t.AddColumn("IsActive", "BIT", False, "1", False, False)
                t.AddColumn("IsDeleted", "BIT", False, "0", False, False)
                t.AddColumn("CreatedAt", "DATETIME2", False, "getdate()", False, False)
                list.Add(t)

                ' ═══════════════════════════════════════════════════════════
                ' جداول البنية التحتية للمزامنة السحابية (Cloud Sync)
                ' ═══════════════════════════════════════════════════════════

                ' S1. _SyncLog (سجل تتبع التغييرات للمزامنة السحابية)
                t = New TableDefinition("_SyncLog", "سجل تتبع التغييرات", "Sync Change Log", True)
                t.AddColumn("LogId", "BIGINT", False, Nothing, True, True)
                t.AddColumn("TableName", "NVARCHAR(128)", False, Nothing, False, False)
                t.AddColumn("RowSyncId", "UNIQUEIDENTIFIER", False, Nothing, False, False)
                t.AddColumn("Operation", "CHAR(1)", False, Nothing, False, False)
                t.AddColumn("ChangedColumns", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("RowDataJson", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("CreatedAt", "DATETIME2", False, "SYSUTCDATETIME()", False, False)
                t.AddColumn("IsSynced", "BIT", False, "0", False, False)
                t.AddColumn("SyncedAt", "DATETIME2", True, Nothing, False, False)
                t.AddColumn("ErrorMessage", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("RetryCount", "INT", False, "0", False, False)
                list.Add(t)

                ' S2. _SyncState (حالة المزامنة لكل جدول)
                t = New TableDefinition("_SyncState", "حالة المزامنة", "Sync State", False)
                t.AddColumn("TableName", "NVARCHAR(128)", False, Nothing, False, True)
                t.AddColumn("LastPushAt", "DATETIME2", True, Nothing, False, False)
                t.AddColumn("LastPullAt", "DATETIME2", True, Nothing, False, False)
                t.AddColumn("LastPullVersion", "BIGINT", False, "0", False, False)
                t.AddColumn("TotalPushed", "BIGINT", False, "0", False, False)
                t.AddColumn("TotalPulled", "BIGINT", False, "0", False, False)
                t.AddColumn("LastError", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("LastErrorAt", "DATETIME2", True, Nothing, False, False)
                list.Add(t)

                ' S3. _SyncConflicts (سجل التعارضات في المزامنة)
                t = New TableDefinition("_SyncConflicts", "تعارضات المزامنة", "Sync Conflicts", True)
                t.AddColumn("ConflictId", "BIGINT", False, Nothing, True, True)
                t.AddColumn("TableName", "NVARCHAR(128)", False, Nothing, False, False)
                t.AddColumn("RowSyncId", "UNIQUEIDENTIFIER", False, Nothing, False, False)
                t.AddColumn("LocalDataJson", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("RemoteDataJson", "NVARCHAR(MAX)", True, Nothing, False, False)
                t.AddColumn("DetectedAt", "DATETIME2", False, "SYSUTCDATETIME()", False, False)
                t.AddColumn("IsResolved", "BIT", False, "0", False, False)
                t.AddColumn("Resolution", "NVARCHAR(20)", True, Nothing, False, False)
                t.AddColumn("ResolvedAt", "DATETIME2", True, Nothing, False, False)
                t.AddColumn("ResolvedBy", "INT", True, Nothing, False, False)
                list.Add(t)

                _schemaTables = list
                Return _schemaTables
            End SyncLock
        End Function

        ''' <summary>إعادة ضبط الكاش الهيكلي</summary>
        Public Sub InvalidateCache()
            SyncLock _lockObj
                _schemaTables = Nothing
            End SyncLock
        End Sub
    End Module
End Namespace
