'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace UC_Main

    <Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()>
    Partial Class UCEmployeesHub
        Inherits System.Windows.Forms.UserControl

        'UserControl overrides dispose to clean up the component list.
        <System.Diagnostics.DebuggerNonUserCode()>
        Protected Overrides Sub Dispose(ByVal disposing As Boolean)
            Try
                If disposing AndAlso components IsNot Nothing Then
                    components.Dispose()
                End If
            Finally
                MyBase.Dispose(disposing)
            End Try
        End Sub

        'Required by the Windows Form Designer
        Private components As System.ComponentModel.IContainer

        'NOTE: The following procedure is required by the Windows Form Designer
        'It can be modified using the Windows Form Designer.
        'Do not modify it using the code editor.
        <System.Diagnostics.DebuggerStepThrough()>
        Private Sub InitializeComponent()
            Me.flpEmployees = New System.Windows.Forms.FlowLayoutPanel()
            Me.pnlHeaderEmployees = New Guna.UI2.WinForms.Guna2Panel()
            Me.btnBackEmployees = New Guna.UI2.WinForms.Guna2Button()
            Me.lblDescEmployees = New System.Windows.Forms.Label()
            Me.lblTitleEmployees = New System.Windows.Forms.Label()
            Me.btnfrmEmployees = New Guna.UI2.WinForms.Guna2Button()
            Me.btnfrmJobTitles = New Guna.UI2.WinForms.Guna2Button()
            Me.btnfrmDepartments = New Guna.UI2.WinForms.Guna2Button()
            Me.btnfrmSalarySystems = New Guna.UI2.WinForms.Guna2Button()
            Me.btnfrmSalaryPayment = New Guna.UI2.WinForms.Guna2Button()
            Me.picHeaderEmployees = New Guna.UI2.WinForms.Guna2PictureBox()
            Me.flpEmployees.SuspendLayout()
            Me.pnlHeaderEmployees.SuspendLayout()
            CType(Me.picHeaderEmployees, System.ComponentModel.ISupportInitialize).BeginInit()
            Me.SuspendLayout()
            '
            'flpEmployees
            '
            Me.flpEmployees.AutoScroll = True
            Me.flpEmployees.Controls.Add(Me.btnfrmEmployees)
            Me.flpEmployees.Controls.Add(Me.btnfrmJobTitles)
            Me.flpEmployees.Controls.Add(Me.btnfrmDepartments)
            Me.flpEmployees.Controls.Add(Me.btnfrmSalarySystems)
            Me.flpEmployees.Controls.Add(Me.btnfrmSalaryPayment)
            Me.flpEmployees.Dock = System.Windows.Forms.DockStyle.Fill
            Me.flpEmployees.FlowDirection = System.Windows.Forms.FlowDirection.RightToLeft
            Me.flpEmployees.Location = New System.Drawing.Point(17, 97)
            Me.flpEmployees.Margin = New System.Windows.Forms.Padding(3, 2, 3, 2)
            Me.flpEmployees.Name = "flpEmployees"
            Me.flpEmployees.Padding = New System.Windows.Forms.Padding(9, 8, 9, 8)
            Me.flpEmployees.RightToLeft = System.Windows.Forms.RightToLeft.No
            Me.flpEmployees.Size = New System.Drawing.Size(977, 503)
            Me.flpEmployees.TabIndex = 0
            '
            'pnlHeaderEmployees
            '
            Me.pnlHeaderEmployees.BorderRadius = 10
            Me.pnlHeaderEmployees.Controls.Add(Me.btnBackEmployees)
            Me.pnlHeaderEmployees.Controls.Add(Me.lblDescEmployees)
            Me.pnlHeaderEmployees.Controls.Add(Me.lblTitleEmployees)
            Me.pnlHeaderEmployees.Controls.Add(Me.picHeaderEmployees)
            Me.pnlHeaderEmployees.Dock = System.Windows.Forms.DockStyle.Top
            Me.pnlHeaderEmployees.Location = New System.Drawing.Point(17, 16)
            Me.pnlHeaderEmployees.Name = "pnlHeaderEmployees"
            Me.pnlHeaderEmployees.Size = New System.Drawing.Size(977, 81)
            Me.pnlHeaderEmployees.TabIndex = 1
            '
            'btnBackEmployees
            '
            Me.btnBackEmployees.BorderRadius = 8
            Me.btnBackEmployees.Cursor = System.Windows.Forms.Cursors.Hand
            Me.btnBackEmployees.FillColor = System.Drawing.Color.FromArgb(CType(CType(30, Byte), Integer), CType(CType(41, Byte), Integer), CType(CType(59, Byte), Integer))
            Me.btnBackEmployees.Font = New System.Drawing.Font("Segoe UI", 9.0!, System.Drawing.FontStyle.Bold)
            Me.btnBackEmployees.ForeColor = System.Drawing.Color.FromArgb(CType(CType(96, Byte), Integer), CType(CType(165, Byte), Integer), CType(CType(250, Byte), Integer))
            Me.btnBackEmployees.ImageAlign = System.Windows.Forms.HorizontalAlignment.Left
            Me.btnBackEmployees.ImageSize = New System.Drawing.Size(16, 16)
            Me.btnBackEmployees.Location = New System.Drawing.Point(15, 19)
            Me.btnBackEmployees.Margin = New System.Windows.Forms.Padding(3, 2, 3, 2)
            Me.btnBackEmployees.Name = "btnBackEmployees"
            Me.btnBackEmployees.RightToLeft = System.Windows.Forms.RightToLeft.Yes
            Me.btnBackEmployees.Size = New System.Drawing.Size(124, 41)
            Me.btnBackEmployees.TabIndex = 4
            Me.btnBackEmployees.Text = "  العودة للرئيسية"
            '
            'lblDescEmployees
            '
            Me.lblDescEmployees.Anchor = CType((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
            Me.lblDescEmployees.BackColor = System.Drawing.Color.Transparent
            Me.lblDescEmployees.Font = New System.Drawing.Font("Segoe UI", 9.0!)
            Me.lblDescEmployees.ForeColor = System.Drawing.Color.FromArgb(CType(CType(148, Byte), Integer), CType(CType(163, Byte), Integer), CType(CType(184, Byte), Integer))
            Me.lblDescEmployees.Location = New System.Drawing.Point(240, 38)
            Me.lblDescEmployees.Name = "lblDescEmployees"
            Me.lblDescEmployees.Padding = New System.Windows.Forms.Padding(0, 7, 13, 0)
            Me.lblDescEmployees.RightToLeft = System.Windows.Forms.RightToLeft.Yes
            Me.lblDescEmployees.Size = New System.Drawing.Size(650, 31)
            Me.lblDescEmployees.TabIndex = 5
            Me.lblDescEmployees.Text = "ملفات العاملين، الشيفات، الويترز، السلف، مسير الرواتب والمكافآت"
            Me.lblDescEmployees.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
            '
            'lblTitleEmployees
            '
            Me.lblTitleEmployees.Anchor = CType((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
            Me.lblTitleEmployees.BackColor = System.Drawing.Color.Transparent
            Me.lblTitleEmployees.Font = New System.Drawing.Font("Segoe UI", 13.0!, System.Drawing.FontStyle.Bold)
            Me.lblTitleEmployees.ForeColor = System.Drawing.Color.White
            Me.lblTitleEmployees.Location = New System.Drawing.Point(398, 8)
            Me.lblTitleEmployees.Name = "lblTitleEmployees"
            Me.lblTitleEmployees.Padding = New System.Windows.Forms.Padding(9, 4, 9, 0)
            Me.lblTitleEmployees.RightToLeft = System.Windows.Forms.RightToLeft.Yes
            Me.lblTitleEmployees.Size = New System.Drawing.Size(492, 30)
            Me.lblTitleEmployees.TabIndex = 6
            Me.lblTitleEmployees.Text = "قسم شؤون الموظفين والرواتب"
            Me.lblTitleEmployees.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
            '
            'btnfrmEmployees
            '
            Me.btnfrmEmployees.BorderColor = System.Drawing.Color.FromArgb(CType(CType(35, Byte), Integer), CType(CType(45, Byte), Integer), CType(CType(63, Byte), Integer))
            Me.btnfrmEmployees.BorderRadius = 12
            Me.btnfrmEmployees.BorderThickness = 1
            Me.btnfrmEmployees.Cursor = System.Windows.Forms.Cursors.Hand
            Me.btnfrmEmployees.FillColor = System.Drawing.Color.FromArgb(CType(CType(20, Byte), Integer), CType(CType(25, Byte), Integer), CType(CType(36, Byte), Integer))
            Me.btnfrmEmployees.Font = New System.Drawing.Font("Segoe UI", 9.5!, System.Drawing.FontStyle.Bold)
            Me.btnfrmEmployees.ForeColor = System.Drawing.Color.White
            Me.btnfrmEmployees.HoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(59, Byte), Integer), CType(CType(130, Byte), Integer), CType(CType(246, Byte), Integer))
            Me.btnfrmEmployees.HoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(37, Byte), Integer), CType(CType(99, Byte), Integer), CType(CType(235, Byte), Integer))
            Me.btnfrmEmployees.HoverState.ForeColor = System.Drawing.Color.White
            Me.btnfrmEmployees.Image = Global.WindowsApp1.My.Resources.Resources.nav_employees_staff_3d
            Me.btnfrmEmployees.ImageAlign = System.Windows.Forms.HorizontalAlignment.Left
            Me.btnfrmEmployees.ImageSize = New System.Drawing.Size(32, 32)
            Me.btnfrmEmployees.Location = New System.Drawing.Point(661, 14)
            Me.btnfrmEmployees.Margin = New System.Windows.Forms.Padding(7, 6, 7, 6)
            Me.btnfrmEmployees.Name = "btnfrmEmployees"
            Me.btnfrmEmployees.RightToLeft = System.Windows.Forms.RightToLeft.Yes
            Me.btnfrmEmployees.Size = New System.Drawing.Size(291, 77)
            Me.btnfrmEmployees.TabIndex = 0
            Me.btnfrmEmployees.Text = "إدارة الموظفين والعاملين" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "سجل العاملين والرواتب والعقود"
            Me.btnfrmEmployees.TextAlign = System.Windows.Forms.HorizontalAlignment.Right
            Me.btnfrmEmployees.TextOffset = New System.Drawing.Point(5, 0)
            '
            'btnfrmJobTitles
            '
            Me.btnfrmJobTitles.BorderColor = System.Drawing.Color.FromArgb(CType(CType(35, Byte), Integer), CType(CType(45, Byte), Integer), CType(CType(63, Byte), Integer))
            Me.btnfrmJobTitles.BorderRadius = 12
            Me.btnfrmJobTitles.BorderThickness = 1
            Me.btnfrmJobTitles.Cursor = System.Windows.Forms.Cursors.Hand
            Me.btnfrmJobTitles.FillColor = System.Drawing.Color.FromArgb(CType(CType(20, Byte), Integer), CType(CType(25, Byte), Integer), CType(CType(36, Byte), Integer))
            Me.btnfrmJobTitles.Font = New System.Drawing.Font("Segoe UI", 9.5!, System.Drawing.FontStyle.Bold)
            Me.btnfrmJobTitles.ForeColor = System.Drawing.Color.White
            Me.btnfrmJobTitles.HoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(59, Byte), Integer), CType(CType(130, Byte), Integer), CType(CType(246, Byte), Integer))
            Me.btnfrmJobTitles.HoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(37, Byte), Integer), CType(CType(99, Byte), Integer), CType(CType(235, Byte), Integer))
            Me.btnfrmJobTitles.HoverState.ForeColor = System.Drawing.Color.White
            Me.btnfrmJobTitles.Image = Global.WindowsApp1.My.Resources.Resources.new_hire
            Me.btnfrmJobTitles.ImageAlign = System.Windows.Forms.HorizontalAlignment.Left
            Me.btnfrmJobTitles.ImageSize = New System.Drawing.Size(32, 32)
            Me.btnfrmJobTitles.Location = New System.Drawing.Point(356, 14)
            Me.btnfrmJobTitles.Margin = New System.Windows.Forms.Padding(7, 6, 7, 6)
            Me.btnfrmJobTitles.Name = "btnfrmJobTitles"
            Me.btnfrmJobTitles.RightToLeft = System.Windows.Forms.RightToLeft.Yes
            Me.btnfrmJobTitles.Size = New System.Drawing.Size(291, 77)
            Me.btnfrmJobTitles.TabIndex = 1
            Me.btnfrmJobTitles.Text = "المسميات الوظيفية" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "كاشير، شيف، ويتر، ديليفري، مدير"
            Me.btnfrmJobTitles.TextAlign = System.Windows.Forms.HorizontalAlignment.Right
            Me.btnfrmJobTitles.TextOffset = New System.Drawing.Point(5, 0)
            '
            'btnfrmDepartments
            '
            Me.btnfrmDepartments.BorderColor = System.Drawing.Color.FromArgb(CType(CType(35, Byte), Integer), CType(CType(45, Byte), Integer), CType(CType(63, Byte), Integer))
            Me.btnfrmDepartments.BorderRadius = 12
            Me.btnfrmDepartments.BorderThickness = 1
            Me.btnfrmDepartments.Cursor = System.Windows.Forms.Cursors.Hand
            Me.btnfrmDepartments.FillColor = System.Drawing.Color.FromArgb(CType(CType(20, Byte), Integer), CType(CType(25, Byte), Integer), CType(CType(36, Byte), Integer))
            Me.btnfrmDepartments.Font = New System.Drawing.Font("Segoe UI", 9.5!, System.Drawing.FontStyle.Bold)
            Me.btnfrmDepartments.ForeColor = System.Drawing.Color.White
            Me.btnfrmDepartments.HoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(59, Byte), Integer), CType(CType(130, Byte), Integer), CType(CType(246, Byte), Integer))
            Me.btnfrmDepartments.HoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(37, Byte), Integer), CType(CType(99, Byte), Integer), CType(CType(235, Byte), Integer))
            Me.btnfrmDepartments.HoverState.ForeColor = System.Drawing.Color.White
            Me.btnfrmDepartments.Image = Global.WindowsApp1.My.Resources.Resources.team
            Me.btnfrmDepartments.ImageAlign = System.Windows.Forms.HorizontalAlignment.Left
            Me.btnfrmDepartments.ImageSize = New System.Drawing.Size(32, 32)
            Me.btnfrmDepartments.Location = New System.Drawing.Point(51, 14)
            Me.btnfrmDepartments.Margin = New System.Windows.Forms.Padding(7, 6, 7, 6)
            Me.btnfrmDepartments.Name = "btnfrmDepartments"
            Me.btnfrmDepartments.RightToLeft = System.Windows.Forms.RightToLeft.Yes
            Me.btnfrmDepartments.Size = New System.Drawing.Size(291, 77)
            Me.btnfrmDepartments.TabIndex = 2
            Me.btnfrmDepartments.Text = "الأقسام الإدارية" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "المطبخ والصالة والديليفري والإدارة"
            Me.btnfrmDepartments.TextAlign = System.Windows.Forms.HorizontalAlignment.Right
            Me.btnfrmDepartments.TextOffset = New System.Drawing.Point(5, 0)
            '
            'btnfrmSalarySystems
            '
            Me.btnfrmSalarySystems.BorderColor = System.Drawing.Color.FromArgb(CType(CType(35, Byte), Integer), CType(CType(45, Byte), Integer), CType(CType(63, Byte), Integer))
            Me.btnfrmSalarySystems.BorderRadius = 12
            Me.btnfrmSalarySystems.BorderThickness = 1
            Me.btnfrmSalarySystems.Cursor = System.Windows.Forms.Cursors.Hand
            Me.btnfrmSalarySystems.FillColor = System.Drawing.Color.FromArgb(CType(CType(20, Byte), Integer), CType(CType(25, Byte), Integer), CType(CType(36, Byte), Integer))
            Me.btnfrmSalarySystems.Font = New System.Drawing.Font("Segoe UI", 9.5!, System.Drawing.FontStyle.Bold)
            Me.btnfrmSalarySystems.ForeColor = System.Drawing.Color.White
            Me.btnfrmSalarySystems.HoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(59, Byte), Integer), CType(CType(130, Byte), Integer), CType(CType(246, Byte), Integer))
            Me.btnfrmSalarySystems.HoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(37, Byte), Integer), CType(CType(99, Byte), Integer), CType(CType(235, Byte), Integer))
            Me.btnfrmSalarySystems.HoverState.ForeColor = System.Drawing.Color.White
            Me.btnfrmSalarySystems.Image = Global.WindowsApp1.My.Resources.Resources.data_processing
            Me.btnfrmSalarySystems.ImageAlign = System.Windows.Forms.HorizontalAlignment.Left
            Me.btnfrmSalarySystems.ImageSize = New System.Drawing.Size(32, 32)
            Me.btnfrmSalarySystems.Location = New System.Drawing.Point(661, 103)
            Me.btnfrmSalarySystems.Margin = New System.Windows.Forms.Padding(7, 6, 7, 6)
            Me.btnfrmSalarySystems.Name = "btnfrmSalarySystems"
            Me.btnfrmSalarySystems.RightToLeft = System.Windows.Forms.RightToLeft.Yes
            Me.btnfrmSalarySystems.Size = New System.Drawing.Size(291, 77)
            Me.btnfrmSalarySystems.TabIndex = 3
            Me.btnfrmSalarySystems.Text = "أنظمة الرواتب والعمولات" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "راتب شهري، يوميات، نسبة مبيعات"
            Me.btnfrmSalarySystems.TextAlign = System.Windows.Forms.HorizontalAlignment.Right
            Me.btnfrmSalarySystems.TextOffset = New System.Drawing.Point(5, 0)
            '
            'btnfrmSalaryPayment
            '
            Me.btnfrmSalaryPayment.BorderColor = System.Drawing.Color.FromArgb(CType(CType(35, Byte), Integer), CType(CType(45, Byte), Integer), CType(CType(63, Byte), Integer))
            Me.btnfrmSalaryPayment.BorderRadius = 12
            Me.btnfrmSalaryPayment.BorderThickness = 1
            Me.btnfrmSalaryPayment.Cursor = System.Windows.Forms.Cursors.Hand
            Me.btnfrmSalaryPayment.FillColor = System.Drawing.Color.FromArgb(CType(CType(20, Byte), Integer), CType(CType(25, Byte), Integer), CType(CType(36, Byte), Integer))
            Me.btnfrmSalaryPayment.Font = New System.Drawing.Font("Segoe UI", 9.5!, System.Drawing.FontStyle.Bold)
            Me.btnfrmSalaryPayment.ForeColor = System.Drawing.Color.White
            Me.btnfrmSalaryPayment.HoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(59, Byte), Integer), CType(CType(130, Byte), Integer), CType(CType(246, Byte), Integer))
            Me.btnfrmSalaryPayment.HoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(37, Byte), Integer), CType(CType(99, Byte), Integer), CType(CType(235, Byte), Integer))
            Me.btnfrmSalaryPayment.HoverState.ForeColor = System.Drawing.Color.White
            Me.btnfrmSalaryPayment.Image = Global.WindowsApp1.My.Resources.Resources.pay__1_
            Me.btnfrmSalaryPayment.ImageAlign = System.Windows.Forms.HorizontalAlignment.Left
            Me.btnfrmSalaryPayment.ImageSize = New System.Drawing.Size(32, 32)
            Me.btnfrmSalaryPayment.Location = New System.Drawing.Point(356, 103)
            Me.btnfrmSalaryPayment.Margin = New System.Windows.Forms.Padding(7, 6, 7, 6)
            Me.btnfrmSalaryPayment.Name = "btnfrmSalaryPayment"
            Me.btnfrmSalaryPayment.RightToLeft = System.Windows.Forms.RightToLeft.Yes
            Me.btnfrmSalaryPayment.Size = New System.Drawing.Size(291, 77)
            Me.btnfrmSalaryPayment.TabIndex = 4
            Me.btnfrmSalaryPayment.Text = "صرف الرواتب والسلف" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "تسليم المرتبات وتوثيق السلف"
            Me.btnfrmSalaryPayment.TextAlign = System.Windows.Forms.HorizontalAlignment.Right
            Me.btnfrmSalaryPayment.TextOffset = New System.Drawing.Point(5, 0)
            '
            'picHeaderEmployees
            '
            Me.picHeaderEmployees.Anchor = CType((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
            Me.picHeaderEmployees.Image = Global.WindowsApp1.My.Resources.Resources.nav_employees_staff_3d
            Me.picHeaderEmployees.ImageRotate = 0!
            Me.picHeaderEmployees.Location = New System.Drawing.Point(898, 9)
            Me.picHeaderEmployees.Margin = New System.Windows.Forms.Padding(3, 2, 3, 2)
            Me.picHeaderEmployees.Name = "picHeaderEmployees"
            Me.picHeaderEmployees.Size = New System.Drawing.Size(64, 64)
            Me.picHeaderEmployees.TabIndex = 7
            Me.picHeaderEmployees.TabStop = False
            '
            'UCEmployeesHub
            '
            Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
            Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
            Me.Controls.Add(Me.flpEmployees)
            Me.Controls.Add(Me.pnlHeaderEmployees)
            Me.Margin = New System.Windows.Forms.Padding(3, 2, 3, 2)
            Me.Name = "UCEmployeesHub"
            Me.Padding = New System.Windows.Forms.Padding(17, 16, 17, 16)
            Me.RightToLeft = System.Windows.Forms.RightToLeft.Yes
            Me.Size = New System.Drawing.Size(1011, 616)
            Me.flpEmployees.ResumeLayout(False)
            Me.pnlHeaderEmployees.ResumeLayout(False)
            CType(Me.picHeaderEmployees, System.ComponentModel.ISupportInitialize).EndInit()
            Me.ResumeLayout(False)

        End Sub

        Friend WithEvents flpEmployees As System.Windows.Forms.FlowLayoutPanel
        Friend WithEvents btnfrmEmployees As Guna.UI2.WinForms.Guna2Button
        Friend WithEvents btnfrmJobTitles As Guna.UI2.WinForms.Guna2Button
        Friend WithEvents btnfrmDepartments As Guna.UI2.WinForms.Guna2Button
        Friend WithEvents btnfrmSalarySystems As Guna.UI2.WinForms.Guna2Button
        Friend WithEvents btnfrmSalaryPayment As Guna.UI2.WinForms.Guna2Button
        Friend WithEvents pnlHeaderEmployees As Guna.UI2.WinForms.Guna2Panel
        Friend WithEvents btnBackEmployees As Guna.UI2.WinForms.Guna2Button
        Friend WithEvents lblDescEmployees As Label
        Friend WithEvents lblTitleEmployees As Label
        Friend WithEvents picHeaderEmployees As Guna.UI2.WinForms.Guna2PictureBox
    End Class

End Namespace
