'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace UC_Main

    <Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()>
    Partial Class UCEmployeesHub
        Inherits System.Windows.Forms.UserControl

        'UserControl overrides dispose to clean up the component list.
        <System.Diagnostics.DebuggerNonUserCode()>
        Protected Overrides Sub Dispose(ByVal disposing As Boolean)
            Try
                If disposing AndAlso components IsNot Nothing Then
                    components.Dispose()
                End If
            Finally
                MyBase.Dispose(disposing)
            End Try
        End Sub

        'Required by the Windows Form Designer
        Private components As System.ComponentModel.IContainer

        'NOTE: The following procedure is required by the Windows Form Designer
        'It can be modified using the Windows Form Designer.
        'Do not modify it using the code editor.
        <System.Diagnostics.DebuggerStepThrough()>
        Private Sub InitializeComponent()
            Me.flpEmployees = New System.Windows.Forms.FlowLayoutPanel()
            Me.pnlHeaderEmployees = New System.Windows.Forms.Panel()
            Me.picHeaderEmployees = New Guna.UI2.WinForms.Guna2PictureBox()
            Me.lblTitleEmployees = New System.Windows.Forms.Label()
            Me.lblDescEmployees = New System.Windows.Forms.Label()
            Me.btnBackEmployees = New Guna.UI2.WinForms.Guna2Button()
            Me.btnfrmEmployees = New Guna.UI2.WinForms.Guna2Button()
            Me.btnfrmJobTitles = New Guna.UI2.WinForms.Guna2Button()
            Me.btnfrmDepartments = New Guna.UI2.WinForms.Guna2Button()
            Me.btnfrmSalarySystems = New Guna.UI2.WinForms.Guna2Button()
            Me.btnfrmSalaryPayment = New Guna.UI2.WinForms.Guna2Button()
            Me.pnlHeaderEmployees.SuspendLayout()
            CType(Me.picHeaderEmployees, System.ComponentModel.ISupportInitialize).BeginInit()
            Me.flpEmployees.SuspendLayout()
            Me.SuspendLayout()

        '
        'pnlHeaderEmployees
        '
        Me.pnlHeaderEmployees.Controls.Add(Me.btnBackEmployees)
        Me.pnlHeaderEmployees.Controls.Add(Me.lblDescEmployees)
        Me.pnlHeaderEmployees.Controls.Add(Me.lblTitleEmployees)
        Me.pnlHeaderEmployees.Controls.Add(Me.picHeaderEmployees)
        Me.pnlHeaderEmployees.Dock = System.Windows.Forms.DockStyle.Top
        Me.pnlHeaderEmployees.Location = New System.Drawing.Point(20, 20)
        Me.pnlHeaderEmployees.Name = "pnlHeaderEmployees"
        Me.pnlHeaderEmployees.Padding = New System.Windows.Forms.Padding(0, 0, 0, 10)
        Me.pnlHeaderEmployees.RightToLeft = System.Windows.Forms.RightToLeft.Yes
        Me.pnlHeaderEmployees.Size = New System.Drawing.Size(1140, 60)
        Me.pnlHeaderEmployees.TabIndex = 1

        '
        'btnBackEmployees
        '
        Me.btnBackEmployees.BorderRadius = 8
        Me.btnBackEmployees.Cursor = System.Windows.Forms.Cursors.Hand
        Me.btnBackEmployees.Dock = System.Windows.Forms.DockStyle.Left
        Me.btnBackEmployees.FillColor = System.Drawing.Color.FromArgb(CType(CType(30, Byte), Integer), CType(CType(41, Byte), Integer), CType(CType(59, Byte), Integer))
        Me.btnBackEmployees.Font = New System.Drawing.Font("Segoe UI", 9.0!, System.Drawing.FontStyle.Bold)
        Me.btnBackEmployees.ForeColor = System.Drawing.Color.FromArgb(CType(CType(96, Byte), Integer), CType(CType(165, Byte), Integer), CType(CType(250, Byte), Integer))
        Me.btnBackEmployees.Image = Global.WindowsApp1.My.Resources.Resources.arrow
        Me.btnBackEmployees.ImageAlign = System.Windows.Forms.HorizontalAlignment.Left
        Me.btnBackEmployees.ImageSize = New System.Drawing.Size(16, 16)
        Me.btnBackEmployees.Location = New System.Drawing.Point(0, 0)
        Me.btnBackEmployees.Name = "btnBackEmployees"
        Me.btnBackEmployees.RightToLeft = System.Windows.Forms.RightToLeft.Yes
        Me.btnBackEmployees.Size = New System.Drawing.Size(145, 50)
        Me.btnBackEmployees.TabIndex = 0
        Me.btnBackEmployees.Text = "  العودة للرئيسية"

        '
        'lblDescEmployees
        '
        Me.lblDescEmployees.AutoSize = True
        Me.lblDescEmployees.Dock = System.Windows.Forms.DockStyle.Right
        Me.lblDescEmployees.Font = New System.Drawing.Font("Segoe UI", 9.0!)
        Me.lblDescEmployees.ForeColor = System.Drawing.Color.FromArgb(CType(CType(148, Byte), Integer), CType(CType(163, Byte), Integer), CType(CType(184, Byte), Integer))
        Me.lblDescEmployees.Location = New System.Drawing.Point(500, 0)
        Me.lblDescEmployees.Name = "lblDescEmployees"
        Me.lblDescEmployees.Padding = New System.Windows.Forms.Padding(0, 9, 15, 0)
        Me.lblDescEmployees.RightToLeft = System.Windows.Forms.RightToLeft.Yes
        Me.lblDescEmployees.Size = New System.Drawing.Size(341, 24)
        Me.lblDescEmployees.TabIndex = 1
        Me.lblDescEmployees.Text = "ملفات العاملين، الشيفات، الويترز، السلف، مسير الرواتب والمكافآت"

        '
        'lblTitleEmployees
        '
        Me.lblTitleEmployees.AutoSize = True
        Me.lblTitleEmployees.Dock = System.Windows.Forms.DockStyle.Right
        Me.lblTitleEmployees.Font = New System.Drawing.Font("Segoe UI", 13.0!, System.Drawing.FontStyle.Bold)
        Me.lblTitleEmployees.ForeColor = System.Drawing.Color.White
        Me.lblTitleEmployees.Location = New System.Drawing.Point(841, 0)
        Me.lblTitleEmployees.Name = "lblTitleEmployees"
        Me.lblTitleEmployees.Padding = New System.Windows.Forms.Padding(10, 5, 10, 0)
        Me.lblTitleEmployees.RightToLeft = System.Windows.Forms.RightToLeft.Yes
        Me.lblTitleEmployees.Size = New System.Drawing.Size(263, 30)
        Me.lblTitleEmployees.TabIndex = 2
        Me.lblTitleEmployees.Text = "قسم شؤون الموظفين والرواتب"

        '
        'picHeaderEmployees
        '
        Me.picHeaderEmployees.Dock = System.Windows.Forms.DockStyle.Right
        Me.picHeaderEmployees.Image = Global.WindowsApp1.My.Resources.Resources.staff
        Me.picHeaderEmployees.ImageRotate = 0!
        Me.picHeaderEmployees.Location = New System.Drawing.Point(1104, 0)
        Me.picHeaderEmployees.Name = "picHeaderEmployees"
        Me.picHeaderEmployees.Size = New System.Drawing.Size(36, 50)
        Me.picHeaderEmployees.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom
        Me.picHeaderEmployees.TabIndex = 3
        Me.picHeaderEmployees.TabStop = False

        '
        'flpEmployees
        '
        Me.flpEmployees.AutoScroll = True
        Me.flpEmployees.Controls.Add(Me.btnfrmEmployees)
        Me.flpEmployees.Controls.Add(Me.btnfrmJobTitles)
        Me.flpEmployees.Controls.Add(Me.btnfrmDepartments)
        Me.flpEmployees.Controls.Add(Me.btnfrmSalarySystems)
        Me.flpEmployees.Controls.Add(Me.btnfrmSalaryPayment)
        Me.flpEmployees.Dock = System.Windows.Forms.DockStyle.Fill
        Me.flpEmployees.FlowDirection = System.Windows.Forms.FlowDirection.RightToLeft
        Me.flpEmployees.Location = New System.Drawing.Point(20, 80)
        Me.flpEmployees.Name = "flpEmployees"
        Me.flpEmployees.Padding = New System.Windows.Forms.Padding(10)
        Me.flpEmployees.RightToLeft = System.Windows.Forms.RightToLeft.Yes
        Me.flpEmployees.Size = New System.Drawing.Size(1140, 658)
        Me.flpEmployees.TabIndex = 0

        '
        'btnfrmEmployees
        '
        Me.btnfrmEmployees.BorderColor = System.Drawing.Color.FromArgb(CType(CType(35, Byte), Integer), CType(CType(45, Byte), Integer), CType(CType(63, Byte), Integer))
        Me.btnfrmEmployees.BorderRadius = 12
        Me.btnfrmEmployees.BorderThickness = 1
        Me.btnfrmEmployees.Cursor = System.Windows.Forms.Cursors.Hand
        Me.btnfrmEmployees.FillColor = System.Drawing.Color.FromArgb(CType(CType(20, Byte), Integer), CType(CType(25, Byte), Integer), CType(CType(36, Byte), Integer))
        Me.btnfrmEmployees.Font = New System.Drawing.Font("Segoe UI", 9.5!, System.Drawing.FontStyle.Bold)
        Me.btnfrmEmployees.ForeColor = System.Drawing.Color.White
        Me.btnfrmEmployees.HoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(59, Byte), Integer), CType(CType(130, Byte), Integer), CType(CType(246, Byte), Integer))
        Me.btnfrmEmployees.HoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(37, Byte), Integer), CType(CType(99, Byte), Integer), CType(CType(235, Byte), Integer))
        Me.btnfrmEmployees.HoverState.ForeColor = System.Drawing.Color.White
        Me.btnfrmEmployees.Image = Global.WindowsApp1.My.Resources.Resources.staff
        Me.btnfrmEmployees.ImageAlign = System.Windows.Forms.HorizontalAlignment.Left
        Me.btnfrmEmployees.ImageSize = New System.Drawing.Size(32, 32)
        Me.btnfrmEmployees.Location = New System.Drawing.Point(18, 18)
        Me.btnfrmEmployees.Margin = New System.Windows.Forms.Padding(8)
        Me.btnfrmEmployees.Name = "btnfrmEmployees"
        Me.btnfrmEmployees.RightToLeft = System.Windows.Forms.RightToLeft.Yes
        Me.btnfrmEmployees.Size = New System.Drawing.Size(340, 95)
        Me.btnfrmEmployees.TabIndex = 0
        Me.btnfrmEmployees.Text = "إدارة الموظفين والعاملين" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "سجل العاملين والرواتب والعقود"
        Me.btnfrmEmployees.TextAlign = System.Windows.Forms.HorizontalAlignment.Right
        Me.btnfrmEmployees.TextOffset = New System.Drawing.Point(5, 0)

        '
        'btnfrmJobTitles
        '
        Me.btnfrmJobTitles.BorderColor = System.Drawing.Color.FromArgb(CType(CType(35, Byte), Integer), CType(CType(45, Byte), Integer), CType(CType(63, Byte), Integer))
        Me.btnfrmJobTitles.BorderRadius = 12
        Me.btnfrmJobTitles.BorderThickness = 1
        Me.btnfrmJobTitles.Cursor = System.Windows.Forms.Cursors.Hand
        Me.btnfrmJobTitles.FillColor = System.Drawing.Color.FromArgb(CType(CType(20, Byte), Integer), CType(CType(25, Byte), Integer), CType(CType(36, Byte), Integer))
        Me.btnfrmJobTitles.Font = New System.Drawing.Font("Segoe UI", 9.5!, System.Drawing.FontStyle.Bold)
        Me.btnfrmJobTitles.ForeColor = System.Drawing.Color.White
        Me.btnfrmJobTitles.HoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(59, Byte), Integer), CType(CType(130, Byte), Integer), CType(CType(246, Byte), Integer))
        Me.btnfrmJobTitles.HoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(37, Byte), Integer), CType(CType(99, Byte), Integer), CType(CType(235, Byte), Integer))
        Me.btnfrmJobTitles.HoverState.ForeColor = System.Drawing.Color.White
        Me.btnfrmJobTitles.Image = Global.WindowsApp1.My.Resources.Resources.new_hire
        Me.btnfrmJobTitles.ImageAlign = System.Windows.Forms.HorizontalAlignment.Left
        Me.btnfrmJobTitles.ImageSize = New System.Drawing.Size(32, 32)
        Me.btnfrmJobTitles.Location = New System.Drawing.Point(374, 18)
        Me.btnfrmJobTitles.Margin = New System.Windows.Forms.Padding(8)
        Me.btnfrmJobTitles.Name = "btnfrmJobTitles"
        Me.btnfrmJobTitles.RightToLeft = System.Windows.Forms.RightToLeft.Yes
        Me.btnfrmJobTitles.Size = New System.Drawing.Size(340, 95)
        Me.btnfrmJobTitles.TabIndex = 1
        Me.btnfrmJobTitles.Text = "المسميات الوظيفية" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "كاشير، شيف، ويتر، ديليفري، مدير"
        Me.btnfrmJobTitles.TextAlign = System.Windows.Forms.HorizontalAlignment.Right
        Me.btnfrmJobTitles.TextOffset = New System.Drawing.Point(5, 0)

        '
        'btnfrmDepartments
        '
        Me.btnfrmDepartments.BorderColor = System.Drawing.Color.FromArgb(CType(CType(35, Byte), Integer), CType(CType(45, Byte), Integer), CType(CType(63, Byte), Integer))
        Me.btnfrmDepartments.BorderRadius = 12
        Me.btnfrmDepartments.BorderThickness = 1
        Me.btnfrmDepartments.Cursor = System.Windows.Forms.Cursors.Hand
        Me.btnfrmDepartments.FillColor = System.Drawing.Color.FromArgb(CType(CType(20, Byte), Integer), CType(CType(25, Byte), Integer), CType(CType(36, Byte), Integer))
        Me.btnfrmDepartments.Font = New System.Drawing.Font("Segoe UI", 9.5!, System.Drawing.FontStyle.Bold)
        Me.btnfrmDepartments.ForeColor = System.Drawing.Color.White
        Me.btnfrmDepartments.HoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(59, Byte), Integer), CType(CType(130, Byte), Integer), CType(CType(246, Byte), Integer))
        Me.btnfrmDepartments.HoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(37, Byte), Integer), CType(CType(99, Byte), Integer), CType(CType(235, Byte), Integer))
        Me.btnfrmDepartments.HoverState.ForeColor = System.Drawing.Color.White
        Me.btnfrmDepartments.Image = Global.WindowsApp1.My.Resources.Resources.team
        Me.btnfrmDepartments.ImageAlign = System.Windows.Forms.HorizontalAlignment.Left
        Me.btnfrmDepartments.ImageSize = New System.Drawing.Size(32, 32)
        Me.btnfrmDepartments.Location = New System.Drawing.Point(730, 18)
        Me.btnfrmDepartments.Margin = New System.Windows.Forms.Padding(8)
        Me.btnfrmDepartments.Name = "btnfrmDepartments"
        Me.btnfrmDepartments.RightToLeft = System.Windows.Forms.RightToLeft.Yes
        Me.btnfrmDepartments.Size = New System.Drawing.Size(340, 95)
        Me.btnfrmDepartments.TabIndex = 2
        Me.btnfrmDepartments.Text = "الأقسام الإدارية" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "المطبخ والصالة والديليفري والإدارة"
        Me.btnfrmDepartments.TextAlign = System.Windows.Forms.HorizontalAlignment.Right
        Me.btnfrmDepartments.TextOffset = New System.Drawing.Point(5, 0)

        '
        'btnfrmSalarySystems
        '
        Me.btnfrmSalarySystems.BorderColor = System.Drawing.Color.FromArgb(CType(CType(35, Byte), Integer), CType(CType(45, Byte), Integer), CType(CType(63, Byte), Integer))
        Me.btnfrmSalarySystems.BorderRadius = 12
        Me.btnfrmSalarySystems.BorderThickness = 1
        Me.btnfrmSalarySystems.Cursor = System.Windows.Forms.Cursors.Hand
        Me.btnfrmSalarySystems.FillColor = System.Drawing.Color.FromArgb(CType(CType(20, Byte), Integer), CType(CType(25, Byte), Integer), CType(CType(36, Byte), Integer))
        Me.btnfrmSalarySystems.Font = New System.Drawing.Font("Segoe UI", 9.5!, System.Drawing.FontStyle.Bold)
        Me.btnfrmSalarySystems.ForeColor = System.Drawing.Color.White
        Me.btnfrmSalarySystems.HoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(59, Byte), Integer), CType(CType(130, Byte), Integer), CType(CType(246, Byte), Integer))
        Me.btnfrmSalarySystems.HoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(37, Byte), Integer), CType(CType(99, Byte), Integer), CType(CType(235, Byte), Integer))
        Me.btnfrmSalarySystems.HoverState.ForeColor = System.Drawing.Color.White
        Me.btnfrmSalarySystems.Image = Global.WindowsApp1.My.Resources.Resources.data_processing
        Me.btnfrmSalarySystems.ImageAlign = System.Windows.Forms.HorizontalAlignment.Left
        Me.btnfrmSalarySystems.ImageSize = New System.Drawing.Size(32, 32)
        Me.btnfrmSalarySystems.Location = New System.Drawing.Point(18, 129)
        Me.btnfrmSalarySystems.Margin = New System.Windows.Forms.Padding(8)
        Me.btnfrmSalarySystems.Name = "btnfrmSalarySystems"
        Me.btnfrmSalarySystems.RightToLeft = System.Windows.Forms.RightToLeft.Yes
        Me.btnfrmSalarySystems.Size = New System.Drawing.Size(340, 95)
        Me.btnfrmSalarySystems.TabIndex = 3
        Me.btnfrmSalarySystems.Text = "أنظمة الرواتب والعمولات" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "راتب شهري، يوميات، نسبة مبيعات"
        Me.btnfrmSalarySystems.TextAlign = System.Windows.Forms.HorizontalAlignment.Right
        Me.btnfrmSalarySystems.TextOffset = New System.Drawing.Point(5, 0)

        '
        'btnfrmSalaryPayment
        '
        Me.btnfrmSalaryPayment.BorderColor = System.Drawing.Color.FromArgb(CType(CType(35, Byte), Integer), CType(CType(45, Byte), Integer), CType(CType(63, Byte), Integer))
        Me.btnfrmSalaryPayment.BorderRadius = 12
        Me.btnfrmSalaryPayment.BorderThickness = 1
        Me.btnfrmSalaryPayment.Cursor = System.Windows.Forms.Cursors.Hand
        Me.btnfrmSalaryPayment.FillColor = System.Drawing.Color.FromArgb(CType(CType(20, Byte), Integer), CType(CType(25, Byte), Integer), CType(CType(36, Byte), Integer))
        Me.btnfrmSalaryPayment.Font = New System.Drawing.Font("Segoe UI", 9.5!, System.Drawing.FontStyle.Bold)
        Me.btnfrmSalaryPayment.ForeColor = System.Drawing.Color.White
        Me.btnfrmSalaryPayment.HoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(59, Byte), Integer), CType(CType(130, Byte), Integer), CType(CType(246, Byte), Integer))
        Me.btnfrmSalaryPayment.HoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(37, Byte), Integer), CType(CType(99, Byte), Integer), CType(CType(235, Byte), Integer))
        Me.btnfrmSalaryPayment.HoverState.ForeColor = System.Drawing.Color.White
        Me.btnfrmSalaryPayment.Image = Global.WindowsApp1.My.Resources.Resources.pay__1_
        Me.btnfrmSalaryPayment.ImageAlign = System.Windows.Forms.HorizontalAlignment.Left
        Me.btnfrmSalaryPayment.ImageSize = New System.Drawing.Size(32, 32)
        Me.btnfrmSalaryPayment.Location = New System.Drawing.Point(374, 129)
        Me.btnfrmSalaryPayment.Margin = New System.Windows.Forms.Padding(8)
        Me.btnfrmSalaryPayment.Name = "btnfrmSalaryPayment"
        Me.btnfrmSalaryPayment.RightToLeft = System.Windows.Forms.RightToLeft.Yes
        Me.btnfrmSalaryPayment.Size = New System.Drawing.Size(340, 95)
        Me.btnfrmSalaryPayment.TabIndex = 4
        Me.btnfrmSalaryPayment.Text = "صرف الرواتب والسلف" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "تسليم المرتبات وتوثيق السلف"
        Me.btnfrmSalaryPayment.TextAlign = System.Windows.Forms.HorizontalAlignment.Right
        Me.btnfrmSalaryPayment.TextOffset = New System.Drawing.Point(5, 0)

        '
        'UCEmployeesHub
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(7.0!, 16.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.Controls.Add(Me.flpEmployees)
        Me.Controls.Add(Me.pnlHeaderEmployees)
        Me.Name = "UCEmployeesHub"
        Me.Padding = New System.Windows.Forms.Padding(20)
        Me.RightToLeft = System.Windows.Forms.RightToLeft.Yes
        Me.Size = New System.Drawing.Size(1180, 758)
            CType(Me.picHeaderEmployees, System.ComponentModel.ISupportInitialize).EndInit()
            Me.pnlHeaderEmployees.ResumeLayout(False)
            Me.pnlHeaderEmployees.PerformLayout()
            Me.flpEmployees.ResumeLayout(False)
            Me.ResumeLayout(False)
        End Sub

        Friend WithEvents flpEmployees As System.Windows.Forms.FlowLayoutPanel
        Friend WithEvents pnlHeaderEmployees As System.Windows.Forms.Panel
        Friend WithEvents picHeaderEmployees As Guna.UI2.WinForms.Guna2PictureBox
        Friend WithEvents lblTitleEmployees As System.Windows.Forms.Label
        Friend WithEvents lblDescEmployees As System.Windows.Forms.Label
        Friend WithEvents btnBackEmployees As Guna.UI2.WinForms.Guna2Button
        Friend WithEvents btnfrmEmployees As Guna.UI2.WinForms.Guna2Button
        Friend WithEvents btnfrmJobTitles As Guna.UI2.WinForms.Guna2Button
        Friend WithEvents btnfrmDepartments As Guna.UI2.WinForms.Guna2Button
        Friend WithEvents btnfrmSalarySystems As Guna.UI2.WinForms.Guna2Button
        Friend WithEvents btnfrmSalaryPayment As Guna.UI2.WinForms.Guna2Button
    End Class

End Namespace