'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace UC_Main

    <Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()>
    Partial Class UCPurchasesHub
        Inherits System.Windows.Forms.UserControl

        'UserControl overrides dispose to clean up the component list.
        <System.Diagnostics.DebuggerNonUserCode()>
        Protected Overrides Sub Dispose(ByVal disposing As Boolean)
            Try
                If disposing AndAlso components IsNot Nothing Then
                    components.Dispose()
                End If
            Finally
                MyBase.Dispose(disposing)
            End Try
        End Sub

        'Required by the Windows Form Designer
        Private components As System.ComponentModel.IContainer

        'NOTE: The following procedure is required by the Windows Form Designer
        'It can be modified using the Windows Form Designer.
        'Do not modify it using the code editor.
        <System.Diagnostics.DebuggerStepThrough()>
        Private Sub InitializeComponent()
            Me.flpPurchases = New System.Windows.Forms.FlowLayoutPanel()
            Me.pnlHeaderPurchases = New System.Windows.Forms.Panel()
            Me.picHeaderPurchases = New Guna.UI2.WinForms.Guna2PictureBox()
            Me.lblTitlePurchases = New System.Windows.Forms.Label()
            Me.lblDescPurchases = New System.Windows.Forms.Label()
            Me.btnBackPurchases = New Guna.UI2.WinForms.Guna2Button()
            Me.btnfrmPurchases = New Guna.UI2.WinForms.Guna2Button()
            Me.btnfrmPurchaseReports = New Guna.UI2.WinForms.Guna2Button()
            Me.pnlHeaderPurchases.SuspendLayout()
            CType(Me.picHeaderPurchases, System.ComponentModel.ISupportInitialize).BeginInit()
            Me.flpPurchases.SuspendLayout()
            Me.SuspendLayout()

        '
        'pnlHeaderPurchases
        '
        Me.pnlHeaderPurchases.Controls.Add(Me.btnBackPurchases)
        Me.pnlHeaderPurchases.Controls.Add(Me.lblDescPurchases)
        Me.pnlHeaderPurchases.Controls.Add(Me.lblTitlePurchases)
        Me.pnlHeaderPurchases.Controls.Add(Me.picHeaderPurchases)
        Me.pnlHeaderPurchases.Dock = System.Windows.Forms.DockStyle.Top
        Me.pnlHeaderPurchases.Location = New System.Drawing.Point(20, 20)
        Me.pnlHeaderPurchases.Name = "pnlHeaderPurchases"
        Me.pnlHeaderPurchases.Padding = New System.Windows.Forms.Padding(0, 0, 0, 10)
        Me.pnlHeaderPurchases.RightToLeft = System.Windows.Forms.RightToLeft.Yes
        Me.pnlHeaderPurchases.Size = New System.Drawing.Size(1140, 60)
        Me.pnlHeaderPurchases.TabIndex = 1

        '
        'btnBackPurchases
        '
        Me.btnBackPurchases.BorderRadius = 8
        Me.btnBackPurchases.Cursor = System.Windows.Forms.Cursors.Hand
        Me.btnBackPurchases.Dock = System.Windows.Forms.DockStyle.Left
        Me.btnBackPurchases.FillColor = System.Drawing.Color.FromArgb(CType(CType(30, Byte), Integer), CType(CType(41, Byte), Integer), CType(CType(59, Byte), Integer))
        Me.btnBackPurchases.Font = New System.Drawing.Font("Segoe UI", 9.0!, System.Drawing.FontStyle.Bold)
        Me.btnBackPurchases.ForeColor = System.Drawing.Color.FromArgb(CType(CType(96, Byte), Integer), CType(CType(165, Byte), Integer), CType(CType(250, Byte), Integer))
        Me.btnBackPurchases.Image = Global.WindowsApp1.My.Resources.Resources.arrow
        Me.btnBackPurchases.ImageAlign = System.Windows.Forms.HorizontalAlignment.Left
        Me.btnBackPurchases.ImageSize = New System.Drawing.Size(16, 16)
        Me.btnBackPurchases.Location = New System.Drawing.Point(0, 0)
        Me.btnBackPurchases.Name = "btnBackPurchases"
        Me.btnBackPurchases.RightToLeft = System.Windows.Forms.RightToLeft.Yes
        Me.btnBackPurchases.Size = New System.Drawing.Size(145, 50)
        Me.btnBackPurchases.TabIndex = 0
        Me.btnBackPurchases.Text = "  العودة للرئيسية"

        '
        'lblDescPurchases
        '
        Me.lblDescPurchases.AutoSize = True
        Me.lblDescPurchases.Dock = System.Windows.Forms.DockStyle.Right
        Me.lblDescPurchases.Font = New System.Drawing.Font("Segoe UI", 9.0!)
        Me.lblDescPurchases.ForeColor = System.Drawing.Color.FromArgb(CType(CType(148, Byte), Integer), CType(CType(163, Byte), Integer), CType(CType(184, Byte), Integer))
        Me.lblDescPurchases.Location = New System.Drawing.Point(549, 0)
        Me.lblDescPurchases.Name = "lblDescPurchases"
        Me.lblDescPurchases.Padding = New System.Windows.Forms.Padding(0, 9, 15, 0)
        Me.lblDescPurchases.RightToLeft = System.Windows.Forms.RightToLeft.Yes
        Me.lblDescPurchases.Size = New System.Drawing.Size(315, 24)
        Me.lblDescPurchases.TabIndex = 1
        Me.lblDescPurchases.Text = "فواتير الشراء، توريدات الخامات، وحسابات المشتريات الشهرية"

        '
        'lblTitlePurchases
        '
        Me.lblTitlePurchases.AutoSize = True
        Me.lblTitlePurchases.Dock = System.Windows.Forms.DockStyle.Right
        Me.lblTitlePurchases.Font = New System.Drawing.Font("Segoe UI", 13.0!, System.Drawing.FontStyle.Bold)
        Me.lblTitlePurchases.ForeColor = System.Drawing.Color.White
        Me.lblTitlePurchases.Location = New System.Drawing.Point(864, 0)
        Me.lblTitlePurchases.Name = "lblTitlePurchases"
        Me.lblTitlePurchases.Padding = New System.Windows.Forms.Padding(10, 5, 10, 0)
        Me.lblTitlePurchases.RightToLeft = System.Windows.Forms.RightToLeft.Yes
        Me.lblTitlePurchases.Size = New System.Drawing.Size(240, 30)
        Me.lblTitlePurchases.TabIndex = 2
        Me.lblTitlePurchases.Text = "قسم المشتريات والتوريدات"

        '
        'picHeaderPurchases
        '
        Me.picHeaderPurchases.Dock = System.Windows.Forms.DockStyle.Right
        Me.picHeaderPurchases.Image = Global.WindowsApp1.My.Resources.Resources.shopping
        Me.picHeaderPurchases.ImageRotate = 0!
        Me.picHeaderPurchases.Location = New System.Drawing.Point(1104, 0)
        Me.picHeaderPurchases.Name = "picHeaderPurchases"
        Me.picHeaderPurchases.Size = New System.Drawing.Size(36, 50)
        Me.picHeaderPurchases.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom
        Me.picHeaderPurchases.TabIndex = 3
        Me.picHeaderPurchases.TabStop = False

        '
        'flpPurchases
        '
        Me.flpPurchases.AutoScroll = True
        Me.flpPurchases.Controls.Add(Me.btnfrmPurchases)
        Me.flpPurchases.Controls.Add(Me.btnfrmPurchaseReports)
        Me.flpPurchases.Dock = System.Windows.Forms.DockStyle.Fill
        Me.flpPurchases.FlowDirection = System.Windows.Forms.FlowDirection.RightToLeft
        Me.flpPurchases.Location = New System.Drawing.Point(20, 80)
        Me.flpPurchases.Name = "flpPurchases"
        Me.flpPurchases.Padding = New System.Windows.Forms.Padding(10)
        Me.flpPurchases.RightToLeft = System.Windows.Forms.RightToLeft.Yes
        Me.flpPurchases.Size = New System.Drawing.Size(1140, 658)
        Me.flpPurchases.TabIndex = 0

        '
        'btnfrmPurchases
        '
        Me.btnfrmPurchases.BorderColor = System.Drawing.Color.FromArgb(CType(CType(35, Byte), Integer), CType(CType(45, Byte), Integer), CType(CType(63, Byte), Integer))
        Me.btnfrmPurchases.BorderRadius = 12
        Me.btnfrmPurchases.BorderThickness = 1
        Me.btnfrmPurchases.Cursor = System.Windows.Forms.Cursors.Hand
        Me.btnfrmPurchases.FillColor = System.Drawing.Color.FromArgb(CType(CType(20, Byte), Integer), CType(CType(25, Byte), Integer), CType(CType(36, Byte), Integer))
        Me.btnfrmPurchases.Font = New System.Drawing.Font("Segoe UI", 9.5!, System.Drawing.FontStyle.Bold)
        Me.btnfrmPurchases.ForeColor = System.Drawing.Color.White
        Me.btnfrmPurchases.HoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(59, Byte), Integer), CType(CType(130, Byte), Integer), CType(CType(246, Byte), Integer))
        Me.btnfrmPurchases.HoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(37, Byte), Integer), CType(CType(99, Byte), Integer), CType(CType(235, Byte), Integer))
        Me.btnfrmPurchases.HoverState.ForeColor = System.Drawing.Color.White
        Me.btnfrmPurchases.Image = Global.WindowsApp1.My.Resources.Resources.shopping
        Me.btnfrmPurchases.ImageAlign = System.Windows.Forms.HorizontalAlignment.Left
        Me.btnfrmPurchases.ImageSize = New System.Drawing.Size(32, 32)
        Me.btnfrmPurchases.Location = New System.Drawing.Point(18, 18)
        Me.btnfrmPurchases.Margin = New System.Windows.Forms.Padding(8)
        Me.btnfrmPurchases.Name = "btnfrmPurchases"
        Me.btnfrmPurchases.RightToLeft = System.Windows.Forms.RightToLeft.Yes
        Me.btnfrmPurchases.Size = New System.Drawing.Size(340, 95)
        Me.btnfrmPurchases.TabIndex = 0
        Me.btnfrmPurchases.Text = "فاتورة مشتريات جديدة" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "توريد خامات ومستلزمات من الموردين"
        Me.btnfrmPurchases.TextAlign = System.Windows.Forms.HorizontalAlignment.Right
        Me.btnfrmPurchases.TextOffset = New System.Drawing.Point(5, 0)

        '
        'btnfrmPurchaseReports
        '
        Me.btnfrmPurchaseReports.BorderColor = System.Drawing.Color.FromArgb(CType(CType(35, Byte), Integer), CType(CType(45, Byte), Integer), CType(CType(63, Byte), Integer))
        Me.btnfrmPurchaseReports.BorderRadius = 12
        Me.btnfrmPurchaseReports.BorderThickness = 1
        Me.btnfrmPurchaseReports.Cursor = System.Windows.Forms.Cursors.Hand
        Me.btnfrmPurchaseReports.FillColor = System.Drawing.Color.FromArgb(CType(CType(20, Byte), Integer), CType(CType(25, Byte), Integer), CType(CType(36, Byte), Integer))
        Me.btnfrmPurchaseReports.Font = New System.Drawing.Font("Segoe UI", 9.5!, System.Drawing.FontStyle.Bold)
        Me.btnfrmPurchaseReports.ForeColor = System.Drawing.Color.White
        Me.btnfrmPurchaseReports.HoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(59, Byte), Integer), CType(CType(130, Byte), Integer), CType(CType(246, Byte), Integer))
        Me.btnfrmPurchaseReports.HoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(37, Byte), Integer), CType(CType(99, Byte), Integer), CType(CType(235, Byte), Integer))
        Me.btnfrmPurchaseReports.HoverState.ForeColor = System.Drawing.Color.White
        Me.btnfrmPurchaseReports.Image = Global.WindowsApp1.My.Resources.Resources.financial
        Me.btnfrmPurchaseReports.ImageAlign = System.Windows.Forms.HorizontalAlignment.Left
        Me.btnfrmPurchaseReports.ImageSize = New System.Drawing.Size(32, 32)
        Me.btnfrmPurchaseReports.Location = New System.Drawing.Point(374, 18)
        Me.btnfrmPurchaseReports.Margin = New System.Windows.Forms.Padding(8)
        Me.btnfrmPurchaseReports.Name = "btnfrmPurchaseReports"
        Me.btnfrmPurchaseReports.RightToLeft = System.Windows.Forms.RightToLeft.Yes
        Me.btnfrmPurchaseReports.Size = New System.Drawing.Size(340, 95)
        Me.btnfrmPurchaseReports.TabIndex = 1
        Me.btnfrmPurchaseReports.Text = "تقارير المشتريات والصرف" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "تحليل تكاليف المشتريات وفواتير الموردين"
        Me.btnfrmPurchaseReports.TextAlign = System.Windows.Forms.HorizontalAlignment.Right
        Me.btnfrmPurchaseReports.TextOffset = New System.Drawing.Point(5, 0)

        '
        'UCPurchasesHub
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(7.0!, 16.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.Controls.Add(Me.flpPurchases)
        Me.Controls.Add(Me.pnlHeaderPurchases)
        Me.Name = "UCPurchasesHub"
        Me.Padding = New System.Windows.Forms.Padding(20)
        Me.RightToLeft = System.Windows.Forms.RightToLeft.Yes
        Me.Size = New System.Drawing.Size(1180, 758)
            CType(Me.picHeaderPurchases, System.ComponentModel.ISupportInitialize).EndInit()
            Me.pnlHeaderPurchases.ResumeLayout(False)
            Me.pnlHeaderPurchases.PerformLayout()
            Me.flpPurchases.ResumeLayout(False)
            Me.ResumeLayout(False)
        End Sub

        Friend WithEvents flpPurchases As System.Windows.Forms.FlowLayoutPanel
        Friend WithEvents pnlHeaderPurchases As System.Windows.Forms.Panel
        Friend WithEvents picHeaderPurchases As Guna.UI2.WinForms.Guna2PictureBox
        Friend WithEvents lblTitlePurchases As System.Windows.Forms.Label
        Friend WithEvents lblDescPurchases As System.Windows.Forms.Label
        Friend WithEvents btnBackPurchases As Guna.UI2.WinForms.Guna2Button
        Friend WithEvents btnfrmPurchases As Guna.UI2.WinForms.Guna2Button
        Friend WithEvents btnfrmPurchaseReports As Guna.UI2.WinForms.Guna2Button
    End Class

End Namespace