'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace UC_Main

    <Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()>
    Partial Class UCTreasuryHub
        Inherits System.Windows.Forms.UserControl

        'UserControl overrides dispose to clean up the component list.
        <System.Diagnostics.DebuggerNonUserCode()>
        Protected Overrides Sub Dispose(ByVal disposing As Boolean)
            Try
                If disposing AndAlso components IsNot Nothing Then
                    components.Dispose()
                End If
            Finally
                MyBase.Dispose(disposing)
            End Try
        End Sub

        'Required by the Windows Form Designer
        Private components As System.ComponentModel.IContainer

        'NOTE: The following procedure is required by the Windows Form Designer
        'It can be modified using the Windows Form Designer.
        'Do not modify it using the code editor.
        <System.Diagnostics.DebuggerStepThrough()>
        Private Sub InitializeComponent()
            Me.flpTreasury = New System.Windows.Forms.FlowLayoutPanel()
            Me.pnlHeaderTreasury = New System.Windows.Forms.Panel()
            Me.picHeaderTreasury = New Guna.UI2.WinForms.Guna2PictureBox()
            Me.lblTitleTreasury = New System.Windows.Forms.Label()
            Me.lblDescTreasury = New System.Windows.Forms.Label()
            Me.btnBackTreasury = New Guna.UI2.WinForms.Guna2Button()
            Me.btnfrmTreasury = New Guna.UI2.WinForms.Guna2Button()
            Me.btnFrmTreasuryTransfer = New Guna.UI2.WinForms.Guna2Button()
            Me.btnDeposit = New Guna.UI2.WinForms.Guna2Button()
            Me.btnWithdraw = New Guna.UI2.WinForms.Guna2Button()
            Me.btnFrmTreasuryTransactionsReport = New Guna.UI2.WinForms.Guna2Button()
            Me.pnlHeaderTreasury.SuspendLayout()
            CType(Me.picHeaderTreasury, System.ComponentModel.ISupportInitialize).BeginInit()
            Me.flpTreasury.SuspendLayout()
            Me.SuspendLayout()

        '
        'pnlHeaderTreasury
        '
        Me.pnlHeaderTreasury.Controls.Add(Me.btnBackTreasury)
        Me.pnlHeaderTreasury.Controls.Add(Me.lblDescTreasury)
        Me.pnlHeaderTreasury.Controls.Add(Me.lblTitleTreasury)
        Me.pnlHeaderTreasury.Controls.Add(Me.picHeaderTreasury)
        Me.pnlHeaderTreasury.Dock = System.Windows.Forms.DockStyle.Top
        Me.pnlHeaderTreasury.Location = New System.Drawing.Point(20, 20)
        Me.pnlHeaderTreasury.Name = "pnlHeaderTreasury"
        Me.pnlHeaderTreasury.Padding = New System.Windows.Forms.Padding(0, 0, 0, 10)
        Me.pnlHeaderTreasury.RightToLeft = System.Windows.Forms.RightToLeft.Yes
        Me.pnlHeaderTreasury.Size = New System.Drawing.Size(1140, 60)
        Me.pnlHeaderTreasury.TabIndex = 1

        '
        'btnBackTreasury
        '
        Me.btnBackTreasury.BorderRadius = 8
        Me.btnBackTreasury.Cursor = System.Windows.Forms.Cursors.Hand
        Me.btnBackTreasury.Dock = System.Windows.Forms.DockStyle.Left
        Me.btnBackTreasury.FillColor = System.Drawing.Color.FromArgb(CType(CType(30, Byte), Integer), CType(CType(41, Byte), Integer), CType(CType(59, Byte), Integer))
        Me.btnBackTreasury.Font = New System.Drawing.Font("Segoe UI", 9.0!, System.Drawing.FontStyle.Bold)
        Me.btnBackTreasury.ForeColor = System.Drawing.Color.FromArgb(CType(CType(96, Byte), Integer), CType(CType(165, Byte), Integer), CType(CType(250, Byte), Integer))
        Me.btnBackTreasury.Image = Global.WindowsApp1.My.Resources.Resources.arrow
        Me.btnBackTreasury.ImageAlign = System.Windows.Forms.HorizontalAlignment.Left
        Me.btnBackTreasury.ImageSize = New System.Drawing.Size(16, 16)
        Me.btnBackTreasury.Location = New System.Drawing.Point(0, 0)
        Me.btnBackTreasury.Name = "btnBackTreasury"
        Me.btnBackTreasury.RightToLeft = System.Windows.Forms.RightToLeft.Yes
        Me.btnBackTreasury.Size = New System.Drawing.Size(145, 50)
        Me.btnBackTreasury.TabIndex = 0
        Me.btnBackTreasury.Text = "  العودة للرئيسية"

        '
        'lblDescTreasury
        '
        Me.lblDescTreasury.AutoSize = True
        Me.lblDescTreasury.Dock = System.Windows.Forms.DockStyle.Right
        Me.lblDescTreasury.Font = New System.Drawing.Font("Segoe UI", 9.0!)
        Me.lblDescTreasury.ForeColor = System.Drawing.Color.FromArgb(CType(CType(148, Byte), Integer), CType(CType(163, Byte), Integer), CType(CType(184, Byte), Integer))
        Me.lblDescTreasury.Location = New System.Drawing.Point(495, 0)
        Me.lblDescTreasury.Name = "lblDescTreasury"
        Me.lblDescTreasury.Padding = New System.Windows.Forms.Padding(0, 9, 15, 0)
        Me.lblDescTreasury.RightToLeft = System.Windows.Forms.RightToLeft.Yes
        Me.lblDescTreasury.Size = New System.Drawing.Size(359, 24)
        Me.lblDescTreasury.TabIndex = 1
        Me.lblDescTreasury.Text = "إدارة الخزن، التحويلات المالية، سندات القبض والصرف، وحركات النقدية"

        '
        'lblTitleTreasury
        '
        Me.lblTitleTreasury.AutoSize = True
        Me.lblTitleTreasury.Dock = System.Windows.Forms.DockStyle.Right
        Me.lblTitleTreasury.Font = New System.Drawing.Font("Segoe UI", 13.0!, System.Drawing.FontStyle.Bold)
        Me.lblTitleTreasury.ForeColor = System.Drawing.Color.White
        Me.lblTitleTreasury.Location = New System.Drawing.Point(854, 0)
        Me.lblTitleTreasury.Name = "lblTitleTreasury"
        Me.lblTitleTreasury.Padding = New System.Windows.Forms.Padding(10, 5, 10, 0)
        Me.lblTitleTreasury.RightToLeft = System.Windows.Forms.RightToLeft.Yes
        Me.lblTitleTreasury.Size = New System.Drawing.Size(250, 30)
        Me.lblTitleTreasury.TabIndex = 2
        Me.lblTitleTreasury.Text = "قسم الخزينة والسيولة النقدية"

        '
        'picHeaderTreasury
        '
        Me.picHeaderTreasury.Dock = System.Windows.Forms.DockStyle.Right
        Me.picHeaderTreasury.Image = Global.WindowsApp1.My.Resources.Resources.treasury
        Me.picHeaderTreasury.ImageRotate = 0!
        Me.picHeaderTreasury.Location = New System.Drawing.Point(1104, 0)
        Me.picHeaderTreasury.Name = "picHeaderTreasury"
        Me.picHeaderTreasury.Size = New System.Drawing.Size(36, 50)
        Me.picHeaderTreasury.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom
        Me.picHeaderTreasury.TabIndex = 3
        Me.picHeaderTreasury.TabStop = False

        '
        'flpTreasury
        '
        Me.flpTreasury.AutoScroll = True
        Me.flpTreasury.Controls.Add(Me.btnfrmTreasury)
        Me.flpTreasury.Controls.Add(Me.btnFrmTreasuryTransfer)
        Me.flpTreasury.Controls.Add(Me.btnDeposit)
        Me.flpTreasury.Controls.Add(Me.btnWithdraw)
        Me.flpTreasury.Controls.Add(Me.btnFrmTreasuryTransactionsReport)
        Me.flpTreasury.Dock = System.Windows.Forms.DockStyle.Fill
        Me.flpTreasury.FlowDirection = System.Windows.Forms.FlowDirection.RightToLeft
        Me.flpTreasury.Location = New System.Drawing.Point(20, 80)
        Me.flpTreasury.Name = "flpTreasury"
        Me.flpTreasury.Padding = New System.Windows.Forms.Padding(10)
        Me.flpTreasury.RightToLeft = System.Windows.Forms.RightToLeft.Yes
        Me.flpTreasury.Size = New System.Drawing.Size(1140, 658)
        Me.flpTreasury.TabIndex = 0

        '
        'btnfrmTreasury
        '
        Me.btnfrmTreasury.BorderColor = System.Drawing.Color.FromArgb(CType(CType(35, Byte), Integer), CType(CType(45, Byte), Integer), CType(CType(63, Byte), Integer))
        Me.btnfrmTreasury.BorderRadius = 12
        Me.btnfrmTreasury.BorderThickness = 1
        Me.btnfrmTreasury.Cursor = System.Windows.Forms.Cursors.Hand
        Me.btnfrmTreasury.FillColor = System.Drawing.Color.FromArgb(CType(CType(20, Byte), Integer), CType(CType(25, Byte), Integer), CType(CType(36, Byte), Integer))
        Me.btnfrmTreasury.Font = New System.Drawing.Font("Segoe UI", 9.5!, System.Drawing.FontStyle.Bold)
        Me.btnfrmTreasury.ForeColor = System.Drawing.Color.White
        Me.btnfrmTreasury.HoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(59, Byte), Integer), CType(CType(130, Byte), Integer), CType(CType(246, Byte), Integer))
        Me.btnfrmTreasury.HoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(37, Byte), Integer), CType(CType(99, Byte), Integer), CType(CType(235, Byte), Integer))
        Me.btnfrmTreasury.HoverState.ForeColor = System.Drawing.Color.White
        Me.btnfrmTreasury.Image = Global.WindowsApp1.My.Resources.Resources.treasury
        Me.btnfrmTreasury.ImageAlign = System.Windows.Forms.HorizontalAlignment.Left
        Me.btnfrmTreasury.ImageSize = New System.Drawing.Size(32, 32)
        Me.btnfrmTreasury.Location = New System.Drawing.Point(18, 18)
        Me.btnfrmTreasury.Margin = New System.Windows.Forms.Padding(8)
        Me.btnfrmTreasury.Name = "btnfrmTreasury"
        Me.btnfrmTreasury.RightToLeft = System.Windows.Forms.RightToLeft.Yes
        Me.btnfrmTreasury.Size = New System.Drawing.Size(340, 95)
        Me.btnfrmTreasury.TabIndex = 0
        Me.btnfrmTreasury.Text = "إدارة الخزن والبنوك" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "خزينة الكاشير والرئيسية والحسابات"
        Me.btnfrmTreasury.TextAlign = System.Windows.Forms.HorizontalAlignment.Right
        Me.btnfrmTreasury.TextOffset = New System.Drawing.Point(5, 0)

        '
        'btnFrmTreasuryTransfer
        '
        Me.btnFrmTreasuryTransfer.BorderColor = System.Drawing.Color.FromArgb(CType(CType(35, Byte), Integer), CType(CType(45, Byte), Integer), CType(CType(63, Byte), Integer))
        Me.btnFrmTreasuryTransfer.BorderRadius = 12
        Me.btnFrmTreasuryTransfer.BorderThickness = 1
        Me.btnFrmTreasuryTransfer.Cursor = System.Windows.Forms.Cursors.Hand
        Me.btnFrmTreasuryTransfer.FillColor = System.Drawing.Color.FromArgb(CType(CType(20, Byte), Integer), CType(CType(25, Byte), Integer), CType(CType(36, Byte), Integer))
        Me.btnFrmTreasuryTransfer.Font = New System.Drawing.Font("Segoe UI", 9.5!, System.Drawing.FontStyle.Bold)
        Me.btnFrmTreasuryTransfer.ForeColor = System.Drawing.Color.White
        Me.btnFrmTreasuryTransfer.HoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(59, Byte), Integer), CType(CType(130, Byte), Integer), CType(CType(246, Byte), Integer))
        Me.btnFrmTreasuryTransfer.HoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(37, Byte), Integer), CType(CType(99, Byte), Integer), CType(CType(235, Byte), Integer))
        Me.btnFrmTreasuryTransfer.HoverState.ForeColor = System.Drawing.Color.White
        Me.btnFrmTreasuryTransfer.Image = Global.WindowsApp1.My.Resources.Resources.exchange
        Me.btnFrmTreasuryTransfer.ImageAlign = System.Windows.Forms.HorizontalAlignment.Left
        Me.btnFrmTreasuryTransfer.ImageSize = New System.Drawing.Size(32, 32)
        Me.btnFrmTreasuryTransfer.Location = New System.Drawing.Point(374, 18)
        Me.btnFrmTreasuryTransfer.Margin = New System.Windows.Forms.Padding(8)
        Me.btnFrmTreasuryTransfer.Name = "btnFrmTreasuryTransfer"
        Me.btnFrmTreasuryTransfer.RightToLeft = System.Windows.Forms.RightToLeft.Yes
        Me.btnFrmTreasuryTransfer.Size = New System.Drawing.Size(340, 95)
        Me.btnFrmTreasuryTransfer.TabIndex = 1
        Me.btnFrmTreasuryTransfer.Text = "تحويل نقدي بين الخزن" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "مناقلة سيولة نقدية بين الخزن وتوثيقها"
        Me.btnFrmTreasuryTransfer.TextAlign = System.Windows.Forms.HorizontalAlignment.Right
        Me.btnFrmTreasuryTransfer.TextOffset = New System.Drawing.Point(5, 0)

        '
        'btnDeposit
        '
        Me.btnDeposit.BorderColor = System.Drawing.Color.FromArgb(CType(CType(35, Byte), Integer), CType(CType(45, Byte), Integer), CType(CType(63, Byte), Integer))
        Me.btnDeposit.BorderRadius = 12
        Me.btnDeposit.BorderThickness = 1
        Me.btnDeposit.Cursor = System.Windows.Forms.Cursors.Hand
        Me.btnDeposit.FillColor = System.Drawing.Color.FromArgb(CType(CType(20, Byte), Integer), CType(CType(25, Byte), Integer), CType(CType(36, Byte), Integer))
        Me.btnDeposit.Font = New System.Drawing.Font("Segoe UI", 9.5!, System.Drawing.FontStyle.Bold)
        Me.btnDeposit.ForeColor = System.Drawing.Color.White
        Me.btnDeposit.HoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(59, Byte), Integer), CType(CType(130, Byte), Integer), CType(CType(246, Byte), Integer))
        Me.btnDeposit.HoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(37, Byte), Integer), CType(CType(99, Byte), Integer), CType(CType(235, Byte), Integer))
        Me.btnDeposit.HoverState.ForeColor = System.Drawing.Color.White
        Me.btnDeposit.Image = Global.WindowsApp1.My.Resources.Resources.deposit
        Me.btnDeposit.ImageAlign = System.Windows.Forms.HorizontalAlignment.Left
        Me.btnDeposit.ImageSize = New System.Drawing.Size(32, 32)
        Me.btnDeposit.Location = New System.Drawing.Point(730, 18)
        Me.btnDeposit.Margin = New System.Windows.Forms.Padding(8)
        Me.btnDeposit.Name = "btnDeposit"
        Me.btnDeposit.RightToLeft = System.Windows.Forms.RightToLeft.Yes
        Me.btnDeposit.Size = New System.Drawing.Size(340, 95)
        Me.btnDeposit.TabIndex = 2
        Me.btnDeposit.Text = "إيداع نقدي (سند قبض)" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "إدخال سيولة إضافية وتحديد جهة الإيداع"
        Me.btnDeposit.TextAlign = System.Windows.Forms.HorizontalAlignment.Right
        Me.btnDeposit.TextOffset = New System.Drawing.Point(5, 0)

        '
        'btnWithdraw
        '
        Me.btnWithdraw.BorderColor = System.Drawing.Color.FromArgb(CType(CType(35, Byte), Integer), CType(CType(45, Byte), Integer), CType(CType(63, Byte), Integer))
        Me.btnWithdraw.BorderRadius = 12
        Me.btnWithdraw.BorderThickness = 1
        Me.btnWithdraw.Cursor = System.Windows.Forms.Cursors.Hand
        Me.btnWithdraw.FillColor = System.Drawing.Color.FromArgb(CType(CType(20, Byte), Integer), CType(CType(25, Byte), Integer), CType(CType(36, Byte), Integer))
        Me.btnWithdraw.Font = New System.Drawing.Font("Segoe UI", 9.5!, System.Drawing.FontStyle.Bold)
        Me.btnWithdraw.ForeColor = System.Drawing.Color.White
        Me.btnWithdraw.HoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(59, Byte), Integer), CType(CType(130, Byte), Integer), CType(CType(246, Byte), Integer))
        Me.btnWithdraw.HoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(37, Byte), Integer), CType(CType(99, Byte), Integer), CType(CType(235, Byte), Integer))
        Me.btnWithdraw.HoverState.ForeColor = System.Drawing.Color.White
        Me.btnWithdraw.Image = Global.WindowsApp1.My.Resources.Resources.paper
        Me.btnWithdraw.ImageAlign = System.Windows.Forms.HorizontalAlignment.Left
        Me.btnWithdraw.ImageSize = New System.Drawing.Size(32, 32)
        Me.btnWithdraw.Location = New System.Drawing.Point(18, 129)
        Me.btnWithdraw.Margin = New System.Windows.Forms.Padding(8)
        Me.btnWithdraw.Name = "btnWithdraw"
        Me.btnWithdraw.RightToLeft = System.Windows.Forms.RightToLeft.Yes
        Me.btnWithdraw.Size = New System.Drawing.Size(340, 95)
        Me.btnWithdraw.TabIndex = 3
        Me.btnWithdraw.Text = "سحب نقدي (سند صرف)" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "سحب سيولة نقدية وتوثيق المسوغ"
        Me.btnWithdraw.TextAlign = System.Windows.Forms.HorizontalAlignment.Right
        Me.btnWithdraw.TextOffset = New System.Drawing.Point(5, 0)

        '
        'btnFrmTreasuryTransactionsReport
        '
        Me.btnFrmTreasuryTransactionsReport.BorderColor = System.Drawing.Color.FromArgb(CType(CType(35, Byte), Integer), CType(CType(45, Byte), Integer), CType(CType(63, Byte), Integer))
        Me.btnFrmTreasuryTransactionsReport.BorderRadius = 12
        Me.btnFrmTreasuryTransactionsReport.BorderThickness = 1
        Me.btnFrmTreasuryTransactionsReport.Cursor = System.Windows.Forms.Cursors.Hand
        Me.btnFrmTreasuryTransactionsReport.FillColor = System.Drawing.Color.FromArgb(CType(CType(20, Byte), Integer), CType(CType(25, Byte), Integer), CType(CType(36, Byte), Integer))
        Me.btnFrmTreasuryTransactionsReport.Font = New System.Drawing.Font("Segoe UI", 9.5!, System.Drawing.FontStyle.Bold)
        Me.btnFrmTreasuryTransactionsReport.ForeColor = System.Drawing.Color.White
        Me.btnFrmTreasuryTransactionsReport.HoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(59, Byte), Integer), CType(CType(130, Byte), Integer), CType(CType(246, Byte), Integer))
        Me.btnFrmTreasuryTransactionsReport.HoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(37, Byte), Integer), CType(CType(99, Byte), Integer), CType(CType(235, Byte), Integer))
        Me.btnFrmTreasuryTransactionsReport.HoverState.ForeColor = System.Drawing.Color.White
        Me.btnFrmTreasuryTransactionsReport.Image = Global.WindowsApp1.My.Resources.Resources.financial
        Me.btnFrmTreasuryTransactionsReport.ImageAlign = System.Windows.Forms.HorizontalAlignment.Left
        Me.btnFrmTreasuryTransactionsReport.ImageSize = New System.Drawing.Size(32, 32)
        Me.btnFrmTreasuryTransactionsReport.Location = New System.Drawing.Point(374, 129)
        Me.btnFrmTreasuryTransactionsReport.Margin = New System.Windows.Forms.Padding(8)
        Me.btnFrmTreasuryTransactionsReport.Name = "btnFrmTreasuryTransactionsReport"
        Me.btnFrmTreasuryTransactionsReport.RightToLeft = System.Windows.Forms.RightToLeft.Yes
        Me.btnFrmTreasuryTransactionsReport.Size = New System.Drawing.Size(340, 95)
        Me.btnFrmTreasuryTransactionsReport.TabIndex = 4
        Me.btnFrmTreasuryTransactionsReport.Text = "تقرير حركة الخزينة والرصيد" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "ميزان النقدية اليومي والأرصدة الدفترية"
        Me.btnFrmTreasuryTransactionsReport.TextAlign = System.Windows.Forms.HorizontalAlignment.Right
        Me.btnFrmTreasuryTransactionsReport.TextOffset = New System.Drawing.Point(5, 0)

        '
        'UCTreasuryHub
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(7.0!, 16.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.Controls.Add(Me.flpTreasury)
        Me.Controls.Add(Me.pnlHeaderTreasury)
        Me.Name = "UCTreasuryHub"
        Me.Padding = New System.Windows.Forms.Padding(20)
        Me.RightToLeft = System.Windows.Forms.RightToLeft.Yes
        Me.Size = New System.Drawing.Size(1180, 758)
            CType(Me.picHeaderTreasury, System.ComponentModel.ISupportInitialize).EndInit()
            Me.pnlHeaderTreasury.ResumeLayout(False)
            Me.pnlHeaderTreasury.PerformLayout()
            Me.flpTreasury.ResumeLayout(False)
            Me.ResumeLayout(False)
        End Sub

        Friend WithEvents flpTreasury As System.Windows.Forms.FlowLayoutPanel
        Friend WithEvents pnlHeaderTreasury As System.Windows.Forms.Panel
        Friend WithEvents picHeaderTreasury As Guna.UI2.WinForms.Guna2PictureBox
        Friend WithEvents lblTitleTreasury As System.Windows.Forms.Label
        Friend WithEvents lblDescTreasury As System.Windows.Forms.Label
        Friend WithEvents btnBackTreasury As Guna.UI2.WinForms.Guna2Button
        Friend WithEvents btnfrmTreasury As Guna.UI2.WinForms.Guna2Button
        Friend WithEvents btnFrmTreasuryTransfer As Guna.UI2.WinForms.Guna2Button
        Friend WithEvents btnDeposit As Guna.UI2.WinForms.Guna2Button
        Friend WithEvents btnWithdraw As Guna.UI2.WinForms.Guna2Button
        Friend WithEvents btnFrmTreasuryTransactionsReport As Guna.UI2.WinForms.Guna2Button
    End Class

End Namespace