'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace UC_Main

    <Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()>
    Partial Class UCUsersHub
        Inherits System.Windows.Forms.UserControl

        'UserControl overrides dispose to clean up the component list.
        <System.Diagnostics.DebuggerNonUserCode()>
        Protected Overrides Sub Dispose(ByVal disposing As Boolean)
            Try
                If disposing AndAlso components IsNot Nothing Then
                    components.Dispose()
                End If
            Finally
                MyBase.Dispose(disposing)
            End Try
        End Sub

        'Required by the Windows Form Designer
        Private components As System.ComponentModel.IContainer

        'NOTE: The following procedure is required by the Windows Form Designer
        'It can be modified using the Windows Form Designer.
        'Do not modify it using the code editor.
        <System.Diagnostics.DebuggerStepThrough()>
        Private Sub InitializeComponent()
            Me.flpUsers = New System.Windows.Forms.FlowLayoutPanel()
            Me.pnlHeaderUsers = New System.Windows.Forms.Panel()
            Me.picHeaderUsers = New Guna.UI2.WinForms.Guna2PictureBox()
            Me.lblTitleUsers = New System.Windows.Forms.Label()
            Me.lblDescUsers = New System.Windows.Forms.Label()
            Me.btnBackUsers = New Guna.UI2.WinForms.Guna2Button()
            Me.btnfrmUsers = New Guna.UI2.WinForms.Guna2Button()
            Me.btnfrmRolesAndPermissions = New Guna.UI2.WinForms.Guna2Button()
            Me.pnlHeaderUsers.SuspendLayout()
            CType(Me.picHeaderUsers, System.ComponentModel.ISupportInitialize).BeginInit()
            Me.flpUsers.SuspendLayout()
            Me.SuspendLayout()

        '
        'pnlHeaderUsers
        '
        Me.pnlHeaderUsers.Controls.Add(Me.btnBackUsers)
        Me.pnlHeaderUsers.Controls.Add(Me.lblDescUsers)
        Me.pnlHeaderUsers.Controls.Add(Me.lblTitleUsers)
        Me.pnlHeaderUsers.Controls.Add(Me.picHeaderUsers)
        Me.pnlHeaderUsers.Dock = System.Windows.Forms.DockStyle.Top
        Me.pnlHeaderUsers.Location = New System.Drawing.Point(20, 20)
        Me.pnlHeaderUsers.Name = "pnlHeaderUsers"
        Me.pnlHeaderUsers.Padding = New System.Windows.Forms.Padding(0, 0, 0, 10)
        Me.pnlHeaderUsers.RightToLeft = System.Windows.Forms.RightToLeft.Yes
        Me.pnlHeaderUsers.Size = New System.Drawing.Size(1140, 60)
        Me.pnlHeaderUsers.TabIndex = 1

        '
        'btnBackUsers
        '
        Me.btnBackUsers.BorderRadius = 8
        Me.btnBackUsers.Cursor = System.Windows.Forms.Cursors.Hand
        Me.btnBackUsers.Dock = System.Windows.Forms.DockStyle.Left
        Me.btnBackUsers.FillColor = System.Drawing.Color.FromArgb(CType(CType(30, Byte), Integer), CType(CType(41, Byte), Integer), CType(CType(59, Byte), Integer))
        Me.btnBackUsers.Font = New System.Drawing.Font("Segoe UI", 9.0!, System.Drawing.FontStyle.Bold)
        Me.btnBackUsers.ForeColor = System.Drawing.Color.FromArgb(CType(CType(96, Byte), Integer), CType(CType(165, Byte), Integer), CType(CType(250, Byte), Integer))
        Me.btnBackUsers.Image = Global.WindowsApp1.My.Resources.Resources.arrow
        Me.btnBackUsers.ImageAlign = System.Windows.Forms.HorizontalAlignment.Left
        Me.btnBackUsers.ImageSize = New System.Drawing.Size(16, 16)
        Me.btnBackUsers.Location = New System.Drawing.Point(0, 0)
        Me.btnBackUsers.Name = "btnBackUsers"
        Me.btnBackUsers.RightToLeft = System.Windows.Forms.RightToLeft.Yes
        Me.btnBackUsers.Size = New System.Drawing.Size(145, 50)
        Me.btnBackUsers.TabIndex = 0
        Me.btnBackUsers.Text = "  العودة للرئيسية"

        '
        'lblDescUsers
        '
        Me.lblDescUsers.AutoSize = True
        Me.lblDescUsers.Dock = System.Windows.Forms.DockStyle.Right
        Me.lblDescUsers.Font = New System.Drawing.Font("Segoe UI", 9.0!)
        Me.lblDescUsers.ForeColor = System.Drawing.Color.FromArgb(CType(CType(148, Byte), Integer), CType(CType(163, Byte), Integer), CType(CType(184, Byte), Integer))
        Me.lblDescUsers.Location = New System.Drawing.Point(448, 0)
        Me.lblDescUsers.Name = "lblDescUsers"
        Me.lblDescUsers.Padding = New System.Windows.Forms.Padding(0, 9, 15, 0)
        Me.lblDescUsers.RightToLeft = System.Windows.Forms.RightToLeft.Yes
        Me.lblDescUsers.Size = New System.Drawing.Size(341, 24)
        Me.lblDescUsers.TabIndex = 1
        Me.lblDescUsers.Text = "حسابات الدخول، كلمات المرور، مصفوفة الصلاحيات، وتأمين النظام"

        '
        'lblTitleUsers
        '
        Me.lblTitleUsers.AutoSize = True
        Me.lblTitleUsers.Dock = System.Windows.Forms.DockStyle.Right
        Me.lblTitleUsers.Font = New System.Drawing.Font("Segoe UI", 13.0!, System.Drawing.FontStyle.Bold)
        Me.lblTitleUsers.ForeColor = System.Drawing.Color.White
        Me.lblTitleUsers.Location = New System.Drawing.Point(789, 0)
        Me.lblTitleUsers.Name = "lblTitleUsers"
        Me.lblTitleUsers.Padding = New System.Windows.Forms.Padding(10, 5, 10, 0)
        Me.lblTitleUsers.RightToLeft = System.Windows.Forms.RightToLeft.Yes
        Me.lblTitleUsers.Size = New System.Drawing.Size(315, 30)
        Me.lblTitleUsers.TabIndex = 2
        Me.lblTitleUsers.Text = "قسم المستخدمين والصلاحيات والأمان"

        '
        'picHeaderUsers
        '
        Me.picHeaderUsers.Dock = System.Windows.Forms.DockStyle.Right
        Me.picHeaderUsers.Image = Global.WindowsApp1.My.Resources.Resources.lock
        Me.picHeaderUsers.ImageRotate = 0!
        Me.picHeaderUsers.Location = New System.Drawing.Point(1104, 0)
        Me.picHeaderUsers.Name = "picHeaderUsers"
        Me.picHeaderUsers.Size = New System.Drawing.Size(36, 50)
        Me.picHeaderUsers.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom
        Me.picHeaderUsers.TabIndex = 3
        Me.picHeaderUsers.TabStop = False

        '
        'flpUsers
        '
        Me.flpUsers.AutoScroll = True
        Me.flpUsers.Controls.Add(Me.btnfrmUsers)
        Me.flpUsers.Controls.Add(Me.btnfrmRolesAndPermissions)
        Me.flpUsers.Dock = System.Windows.Forms.DockStyle.Fill
        Me.flpUsers.FlowDirection = System.Windows.Forms.FlowDirection.RightToLeft
        Me.flpUsers.Location = New System.Drawing.Point(20, 80)
        Me.flpUsers.Name = "flpUsers"
        Me.flpUsers.Padding = New System.Windows.Forms.Padding(10)
        Me.flpUsers.RightToLeft = System.Windows.Forms.RightToLeft.Yes
        Me.flpUsers.Size = New System.Drawing.Size(1140, 658)
        Me.flpUsers.TabIndex = 0

        '
        'btnfrmUsers
        '
        Me.btnfrmUsers.BorderColor = System.Drawing.Color.FromArgb(CType(CType(35, Byte), Integer), CType(CType(45, Byte), Integer), CType(CType(63, Byte), Integer))
        Me.btnfrmUsers.BorderRadius = 12
        Me.btnfrmUsers.BorderThickness = 1
        Me.btnfrmUsers.Cursor = System.Windows.Forms.Cursors.Hand
        Me.btnfrmUsers.FillColor = System.Drawing.Color.FromArgb(CType(CType(20, Byte), Integer), CType(CType(25, Byte), Integer), CType(CType(36, Byte), Integer))
        Me.btnfrmUsers.Font = New System.Drawing.Font("Segoe UI", 9.5!, System.Drawing.FontStyle.Bold)
        Me.btnfrmUsers.ForeColor = System.Drawing.Color.White
        Me.btnfrmUsers.HoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(59, Byte), Integer), CType(CType(130, Byte), Integer), CType(CType(246, Byte), Integer))
        Me.btnfrmUsers.HoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(37, Byte), Integer), CType(CType(99, Byte), Integer), CType(CType(235, Byte), Integer))
        Me.btnfrmUsers.HoverState.ForeColor = System.Drawing.Color.White
        Me.btnfrmUsers.Image = Global.WindowsApp1.My.Resources.Resources.user
        Me.btnfrmUsers.ImageAlign = System.Windows.Forms.HorizontalAlignment.Left
        Me.btnfrmUsers.ImageSize = New System.Drawing.Size(32, 32)
        Me.btnfrmUsers.Location = New System.Drawing.Point(18, 18)
        Me.btnfrmUsers.Margin = New System.Windows.Forms.Padding(8)
        Me.btnfrmUsers.Name = "btnfrmUsers"
        Me.btnfrmUsers.RightToLeft = System.Windows.Forms.RightToLeft.Yes
        Me.btnfrmUsers.Size = New System.Drawing.Size(340, 95)
        Me.btnfrmUsers.TabIndex = 0
        Me.btnfrmUsers.Text = "إدارة حسابات المستخدمين" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "إنشاء وتعديل حسابات الكاشير والمشرفين"
        Me.btnfrmUsers.TextAlign = System.Windows.Forms.HorizontalAlignment.Right
        Me.btnfrmUsers.TextOffset = New System.Drawing.Point(5, 0)

        '
        'btnfrmRolesAndPermissions
        '
        Me.btnfrmRolesAndPermissions.BorderColor = System.Drawing.Color.FromArgb(CType(CType(35, Byte), Integer), CType(CType(45, Byte), Integer), CType(CType(63, Byte), Integer))
        Me.btnfrmRolesAndPermissions.BorderRadius = 12
        Me.btnfrmRolesAndPermissions.BorderThickness = 1
        Me.btnfrmRolesAndPermissions.Cursor = System.Windows.Forms.Cursors.Hand
        Me.btnfrmRolesAndPermissions.FillColor = System.Drawing.Color.FromArgb(CType(CType(20, Byte), Integer), CType(CType(25, Byte), Integer), CType(CType(36, Byte), Integer))
        Me.btnfrmRolesAndPermissions.Font = New System.Drawing.Font("Segoe UI", 9.5!, System.Drawing.FontStyle.Bold)
        Me.btnfrmRolesAndPermissions.ForeColor = System.Drawing.Color.White
        Me.btnfrmRolesAndPermissions.HoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(59, Byte), Integer), CType(CType(130, Byte), Integer), CType(CType(246, Byte), Integer))
        Me.btnfrmRolesAndPermissions.HoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(37, Byte), Integer), CType(CType(99, Byte), Integer), CType(CType(235, Byte), Integer))
        Me.btnfrmRolesAndPermissions.HoverState.ForeColor = System.Drawing.Color.White
        Me.btnfrmRolesAndPermissions.Image = Global.WindowsApp1.My.Resources.Resources.lock
        Me.btnfrmRolesAndPermissions.ImageAlign = System.Windows.Forms.HorizontalAlignment.Left
        Me.btnfrmRolesAndPermissions.ImageSize = New System.Drawing.Size(32, 32)
        Me.btnfrmRolesAndPermissions.Location = New System.Drawing.Point(374, 18)
        Me.btnfrmRolesAndPermissions.Margin = New System.Windows.Forms.Padding(8)
        Me.btnfrmRolesAndPermissions.Name = "btnfrmRolesAndPermissions"
        Me.btnfrmRolesAndPermissions.RightToLeft = System.Windows.Forms.RightToLeft.Yes
        Me.btnfrmRolesAndPermissions.Size = New System.Drawing.Size(340, 95)
        Me.btnfrmRolesAndPermissions.TabIndex = 1
        Me.btnfrmRolesAndPermissions.Text = "الأدوار ومصفوفة الصلاحيات" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "صلاحيات الخصم والإلغاء والتقارير"
        Me.btnfrmRolesAndPermissions.TextAlign = System.Windows.Forms.HorizontalAlignment.Right
        Me.btnfrmRolesAndPermissions.TextOffset = New System.Drawing.Point(5, 0)

        '
        'UCUsersHub
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(7.0!, 16.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.Controls.Add(Me.flpUsers)
        Me.Controls.Add(Me.pnlHeaderUsers)
        Me.Name = "UCUsersHub"
        Me.Padding = New System.Windows.Forms.Padding(20)
        Me.RightToLeft = System.Windows.Forms.RightToLeft.Yes
        Me.Size = New System.Drawing.Size(1180, 758)
            CType(Me.picHeaderUsers, System.ComponentModel.ISupportInitialize).EndInit()
            Me.pnlHeaderUsers.ResumeLayout(False)
            Me.pnlHeaderUsers.PerformLayout()
            Me.flpUsers.ResumeLayout(False)
            Me.ResumeLayout(False)
        End Sub

        Friend WithEvents flpUsers As System.Windows.Forms.FlowLayoutPanel
        Friend WithEvents pnlHeaderUsers As System.Windows.Forms.Panel
        Friend WithEvents picHeaderUsers As Guna.UI2.WinForms.Guna2PictureBox
        Friend WithEvents lblTitleUsers As System.Windows.Forms.Label
        Friend WithEvents lblDescUsers As System.Windows.Forms.Label
        Friend WithEvents btnBackUsers As Guna.UI2.WinForms.Guna2Button
        Friend WithEvents btnfrmUsers As Guna.UI2.WinForms.Guna2Button
        Friend WithEvents btnfrmRolesAndPermissions As Guna.UI2.WinForms.Guna2Button
    End Class

End Namespace